COM-1910 - Prevent step deletion if step is linked to courseSlot
sophiemoustard/alenvi-webapp pull request #1004
Opened 2021-03-04 16:36 UTC by KennyCallegari

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~

- [ ] J'ai verifié la fonctionnalite sur mobile -np

- Périmetre interface : vendor

- Périmetre roles : trainer / admin

- Cas d'usage : 
Je ne peux pas supprimer une étape lié à un créneau

2021-03-04 18:28 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.status === 409) return NotifyWarning('Impossible de retirer l\'étape tant qu\'elle lié à un créneau');
pour rester coherent avec les autres messages (celui des catégories notamment) tu peux mettre : 
'Certains créneaux de formation sont encore rattachés à cette étape.'

2021-03-04 18:29 UTC, sophiemoustard commented
on pourrait egalement mettre en place un virtual qui compte les creneaux d'une formation et faire directement le blocage en front. qu'en penses tu ?

2021-03-05 09:26 UTC, ulysseferreira commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.status === 409) return NotifyWarning('Impossible de retirer l\'étape tant qu\'elle lié à un créneau');
t'as oublié un mot entre elle et lié ;) et liéE avec un E

2021-03-05 09:53 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.status === 409) return NotifyWarning('Impossible de retirer l\'étape tant qu\'elle lié à un créneau');
done

2021-03-05 09:54 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.status === 409) return NotifyWarning('Impossible de retirer l\'étape tant qu\'elle lié à un créneau');
merci ! j'ai pris la phrase de Sophie du coup, au moins il n'y a pas de faute dans la sienne 😄

2021-03-05 10:02 UTC, ulysseferreira approved these changes

2021-03-05 15:49 UTC, ulysseferreira commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        return NotifyNegative('Erreur lors du retrait de l\'étape.');
pourquoi des fois on met return et des fois non ?

2021-03-05 15:54 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        return NotifyNegative('Erreur lors du retrait de l\'étape.');
On met un return si on ne veut pas affiché 2 notifyNegative : 
```
if (e.status === 409) NotifyNegative(skusku)
NotifyNegative(skusku 2)

```
va afficher skusku et skusku2 si on reçoit une 409. Donc on met des return pour sortir du catch.

Mais là ça ne sert à rien effectivement 😄

2021-03-05 16:13 UTC, sophiemoustard requested changes

2021-03-05 16:13 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        return NotifyNegative('Erreur lors du retrait de l\'étape.');
tu peux laisser aussi la verification sur le retour du back :) avec le bon meessage d'erreur

2021-03-05 16:25 UTC, sophiemoustard approved these changes

2021-03-05 16:42 UTC, ulysseferreira approved these changes

2021-03-05 17:13 UTC, merged