Com 1925 2
sophiemoustard/alenvi-webapp pull request #1022
Opened 2021-03-17 15:49 UTC by KennyCallegari

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach / client admin / vendor / rof

- Cas d'usage : 
J'ai accès à l'onglet 'Suivi des stagiaires' dans la page profil d'une formation mixte intra dans l'interface client.
En tant que coach / client admin, je ne peux pas modifier le tableau de présence ni ajouter/supprimer une fiche de présence.

2021-03-18 16:08 UTC, cmolle commented on src/core/components/table/AttendanceTable.vue
> -        NotifyPositive('Participant ajouté.');
Pourquoi l'avoir supprimé ?

2021-03-18 16:08 UTC, cmolle commented on src/core/helpers/ability.js
> +  if ([VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER].includes(vendorRole)) can('update', 'course_trainee_follow_up');
Il y a les formateurs aussi dans certains conditions

2021-03-18 17:06 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de l\'ajout de la feuille d\'émargement.');
Que penses tu de mettre "Impossible d'ajouter une feuille d'emargement." comme message d'erreur ?

2021-03-18 17:11 UTC, sophiemoustard requested changes

2021-03-18 17:11 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        return NotifyNegative('Erreur lors de la suppression de la feuille d\'émargement.');
idem ici

2021-03-18 17:11 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +      if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de la suppression de l\'émargement.');
idem que penses tu d'utiliser la tournure "impossible..."

2021-03-18 17:11 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +        if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de l\'ajout du participant.');
idem

2021-03-18 17:11 UTC, sophiemoustard commented on src/core/helpers/ability.js
> +  if ([VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER].includes(vendorRole)) can('update', 'course_trainee_follow_up');
peut etre qu'on peut mettre ici simplement 
```
  if ([VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER, TRAINER].includes(vendorRole)) can('update', 'course_trainee_follow_up');
```
car noramlement le front gere deja le blocage de l'acces a la page si la personne n'est pas le formateur de la formation + le back bloque les actions dans ces cas la

2021-03-19 13:31 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
> -        NotifyPositive('Participant ajouté.');
erreur de ma part, je vois pas pourquoi je l'aurai supprimé

2021-03-19 13:31 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
> +        if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de l\'ajout du participant.');
done

2021-03-19 13:31 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
> +      if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de la suppression de l\'émargement.');
done

2021-03-19 13:31 UTC, KennyCallegari commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        return NotifyNegative('Erreur lors de la suppression de la feuille d\'émargement.');
done

2021-03-19 13:31 UTC, KennyCallegari commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        if (!this.canUpdateAttendance) return NotifyNegative('Erreur lors de l\'ajout de la feuille d\'émargement.');
done

2021-03-19 13:34 UTC, KennyCallegari commented on src/core/helpers/ability.js
> +  if ([VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER].includes(vendorRole)) can('update', 'course_trainee_follow_up');
done

2021-03-22 14:37 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +            ...this.attendances.filter(a => a.courseSlot !== query.courseSlot),
comme icic tu utilises `query.courseSlot` ce serait plus logique de baser la condition de ton if dessus

2021-03-22 14:50 UTC, sophiemoustard requested changes

2021-03-22 14:50 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      }
ca tient sur une ligne

2021-03-22 15:12 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
> +            ...this.attendances.filter(a => a.courseSlot !== query.courseSlot),
done

2021-03-22 15:13 UTC, KennyCallegari commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      }
done

2021-03-22 15:30 UTC, sophiemoustard approved these changes

2021-03-22 15:53 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
>      <div v-if="noSlots" class="text-center text-italic q-pa-lg no-data">
peux tu corriger aussi la coquielles noSlot et non noSlots ^^

2021-03-22 15:56 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
>      <div v-if="noSlots" class="text-center text-italic q-pa-lg no-data">
done

2021-03-22 16:06 UTC, cmolle reviewed
Est-ce qu'on veut que sur l'interface client quelqu'un qui a un role vendeur puisse ajouter des emargements ?

2021-03-22 16:16 UTC, KennyCallegari commented on src/core/components/table/AttendanceTable.vue
> +    <ni-button v-if="course.slots.length && canUpdateAttendance" color="primary" icon="add" class="q-mb-sm"
done

2021-03-22 16:18 UTC, KennyCallegari commented
> Est-ce qu'on veut que sur l'interface client quelqu'un qui a un role vendeur puisse ajouter des émargements ?

Je suis parti du principe que oui, puisque l'utilisateur peut le modifier du côté vendeur et que c'est plus facile de le laisser faire côté client (niveau code), ça me paraissait logique.
Qu'en pensez-vous ?

2021-03-22 16:58 UTC, sophiemoustard commented
> > Est-ce qu'on veut que sur l'interface client quelqu'un qui a un role vendeur puisse ajouter des émargements ?
> 
> Je suis parti du principe que oui, puisque l'utilisateur peut le modifier du côté vendeur et que c'est plus facile de le laisser faire côté client (niveau code), ça me paraissait logique.
> Qu'en pensez-vous ?

je suis partie du meme postulat

2021-03-22 17:01 UTC, sophiemoustard approved these changes

2021-03-23 08:05 UTC, cmolle approved these changes

2021-03-23 11:32 UTC, ulysseferreira approved these changes

2021-03-23 14:09 UTC, merged