Com 1956
sophiemoustard/alenvi-webapp pull request #1024
Opened 2021-03-18 10:26 UTC by cmolle

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : ROF/admin

- Cas d'usage : Je peux ajouter des testeurs a un programme

2021-03-18 13:36 UTC, KennyCallegari commented on src/modules/vendor/components/programs/TesterTable.vue
> +
saut de ligne en trop 😄

2021-03-18 13:36 UTC, KennyCallegari commented on src/modules/vendor/components/programs/TesterTable.vue
> +        if (e.status === 409) return NotifyNegative(e.data.message);
si tu return dans le catch, tu passes quand même dans le finally ?

2021-03-18 13:36 UTC, KennyCallegari commented on src/modules/vendor/components/programs/TesterTable.vue
> +      this.addnewTesterIdentityStep = false;
add**N**ew* 😄

2021-03-18 15:26 UTC, cmolle commented on src/modules/vendor/components/programs/TesterTable.vue
> +
Done!

2021-03-18 15:26 UTC, cmolle commented on src/modules/vendor/components/programs/TesterTable.vue
> +      this.addnewTesterIdentityStep = false;
Done !

2021-03-18 15:32 UTC, cmolle commented on src/modules/vendor/components/programs/TesterTable.vue
> +        if (e.status === 409) return NotifyNegative(e.data.message);
Bien vu ! Je ne m'etais pas posee la question mais du coup oui ^^ https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/try...catch#la_clause_finally
https://stackoverflow.com/questions/15225819/try-catch-finally-return-clarification

2021-03-18 15:40 UTC, KennyCallegari approved these changes

2021-03-18 16:16 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +        if (e.status === 409) return NotifyNegative(e.data.message);
dans tous les cas on passe par le `finally` qeu tu passes dnas le catch ou non, que tu retournes un resultat dans le catch ou dans le try

2021-03-18 16:25 UTC, sophiemoustard requested changes

2021-03-18 16:25 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +  name: 'TraineeTable',
testerTable

2021-03-18 16:36 UTC, sophiemoustard requested changes

2021-03-18 16:36 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +          format: value => formatPhone(value),
`format: formatPhone` fonctionne

2021-03-18 16:36 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +      testersPagination: { rowsPerPage: 0, sortBy: 'lastname' },
tu pourrais simplement appeler ca pagination - comme le composant s'appelle `TesterTable` on sait de quel tableau on parle

2021-03-18 16:36 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +      testerCreationModalLoading: false,
que penses tu de le simplifier en `modalLoading` ?

2021-03-18 16:36 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +        NotifyPositive('Testeur ajouté avec succès');
peux tu mettre un . a la fin de la phrase stp ?

2021-03-18 16:36 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +          NotifyPositive('Testeur ajouté avec succès');
idem pour le .

2021-03-18 16:39 UTC, sophiemoustard requested changes

2021-03-18 16:39 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterCreationModal.vue
> +  name: 'LearnerCreationModal',
a changer

2021-03-19 10:56 UTC, ulysseferreira approved these changes

2021-03-22 08:22 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +        NotifyNegative('Erreur lors de l\'ajout du stagiaire.');
message d'erreur a changer

2021-03-22 08:23 UTC, sophiemoustard requested changes

2021-03-22 08:23 UTC, sophiemoustard commented on src/modules/vendor/components/programs/TesterTable.vue
> +        NotifyPositive('Email envoyé');
peux tu mettre un . ?

2021-03-22 08:59 UTC, sophiemoustard approved these changes

2021-03-22 08:59 UTC, merged