Com 1946 creation
sophiemoustard/alenvi-webapp pull request #1037
Opened 2021-03-24 17:02 UTC by cmolle

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach/admin

- Cas d'usage : vue no mutating props poru la creation d'avoirs
Tester les pages utilisant dateRange et dateTimeRange :
- planning
- contrat/version
- export
- ajout de creneau dans une formation
- facturation
- page facturation beneficiaire (cote beneficiaire egalement)
- tableau de bord formation
- page suivi contrat
- page suivi absence

2021-03-24 17:04 UTC, sophiemoustard commented on src/core/helpers/vuelidateCustomVal.js
> +export const minDate = min => value => new Date(min) <= new Date(value);
👍

2021-03-24 17:05 UTC, sophiemoustard reviewed
je crois que tu peux enlever le blocage de la regle dans eslintrc du coup

2021-03-24 17:34 UTC, sophiemoustard commented on .eslintrc.js
> +    'vue/no-mutating-props': 1,
je pense que tu peux carrement retirer la ligne car c'est la configuration par defaut

2021-03-24 17:41 UTC, sophiemoustard requested changes

2021-03-24 17:41 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      :disable="thirdPartyPayerOptions.length === 0" />
ca tient sur 2 lignes

2021-03-24 17:41 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      <q-toggle :value="hasLinkedEvents" @input="updateHasLinkedEvents($event)" label="Lié à des interventions ?" />
es tu obligé d'ajouter l'argument ? n'est il pas la par defaut ?

2021-03-24 17:41 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        @input="update($event, 'inclTaxesTpp')" />
ca tient en 3 lignes

2021-03-24 17:41 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +    },
en fait, est ce que ca pourrait etre gérer par un `watch` dans le parent ?

2021-03-24 17:41 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        :max="minAndMaxDates.maxStartDate" />
idem

2021-03-25 12:45 UTC, KennyCallegari commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +    resetData () {
On passe déjà `resetCreationModalData` à la modale, quelle est la différence avec cette fonction ?
(Tu peux aussi reset `hasLinkedEvents` ici)

2021-03-25 12:45 UTC, KennyCallegari commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +      this.resetData();
Juste au dessus, `pagination` tient sur une ligne

2021-03-25 13:10 UTC, cmolle commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +    resetData () {
On ne reset pas tout ici, on reset uniquement la partie basse de la modale (celle lie a hasLinkedEvent). Du coup je ne peux pas reinitialiser hasLinkedEvent car justement ctte mthode est appelé lorsqu'elle change de valeur. 

J'ai aussi decide de l'appeler quand le beneficiaire est changé car il fallait au moins reinitialise la partie souscription et evenements, du coup je me suis dit qu'on pouvait reinitialise le reste. 
Tu en penses quoi ? 

Je peux peut etre renommer la methode pour qu'elle soit plus precise ?

2021-03-25 13:42 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      this.$emit('reset-data');
je ne comprends pas ton resetData ? pourquoi ne pas utiliser un watcher dans le parent ?

2021-03-25 13:49 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      this.$emit('reset-data');
Le probleme c'est que j'ai l'impression que le watcher n'est pas synchrone. Et j'ai besoin que ce soit reinitialise avant d'appeler getEvents, sinon ca recupere les evenements du beneficiaire precedent. C'est pour ca que je suis passee du watcher a l'emission d'un evenement.

2021-03-25 13:56 UTC, KennyCallegari commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +    resetData () {
Ha oui tout à fait !
Que penses-tu de ce code dans ce cas (pour comprendre que seulement une partie est modifiée) :
```
this.creditNoteEvents = [];
this.newCreditNote = {
      ...this.newCreditNote,
      events: [];
      subscription: null;
      startDate: '';
      endDate = '';
      exclTaxesCustomer = 0;
      inclTaxesCustomer = 0;
      exclTaxesTpp = 0;
      inclTaxesTpp = 0;
}
this.$v.newCreditNote.startDate.$reset();
this.$v.newCreditNote.endDate.$reset();
this.$v.newCreditNote.subscription.$reset();
this.$v.newCreditNote.inclTaxesCustomer.$reset();
this.$v.newCreditNote.inclTaxesTpp.$reset();
```
Et peut-être appeler la fonction `resetCustomerData()` ?

2021-03-25 14:06 UTC, KennyCallegari commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +
petit saut de ligne en trop je crois 😄

2021-03-25 14:13 UTC, KennyCallegari approved these changes

2021-03-25 14:45 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +
je le trouve bien ^^

2021-03-25 14:47 UTC, sophiemoustard approved these changes

2021-03-25 14:48 UTC, merged