COM-1951: remove questionnaire
sophiemoustard/alenvi-webapp pull request #1040
Opened 2021-03-26 10:07 UTC by ulysseferreira

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile -np

- Périmetre interface : -np

- Périmetre roles : -np

- Cas d'usage : retirer tout ce qui touche aux activités questionnaire

2021-03-26 15:45 UTC, cmolle approved these changes

2021-03-26 16:19 UTC, KennyCallegari approved these changes

2021-03-29 07:03 UTC, sophiemoustard requested changes

2021-03-29 07:25 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
>  .two-lines
done

2021-03-29 07:30 UTC, sophiemoustard approved these changes

2021-03-29 07:31 UTC, merged