Com 1981
sophiemoustard/alenvi-webapp pull request #1059
Opened 2021-04-08 14:27 UTC by KennyCallegari

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendor

- Périmetre roles : rof / trainer

- Cas d'usage : 
Je peux filter le kanban (répertoire courses mixtes) par référent compani.

2021-04-08 17:08 UTC, sophiemoustard commented on src/core/mixins/courseFiltersMixin.js
> +        .sort((a, b) => a.label.localeCompare(b.label));
la methode `formatAndSortString` fait le taf non ?

2021-04-08 19:32 UTC, ulysseferreira reviewed
c'est volontaire que sur mobile les selectors soient alignés à droite ?

2021-04-09 08:19 UTC, sophiemoustard reviewed
> c'est volontaire que sur mobile les selectors soient alignés à droite ?

pour ca que penses tu de passer par du css grid plutot que boostrap ? je t'ai fait une proposition en commentaire

2021-04-09 08:21 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      <div class="col-xs-12 col-sm-6 col-md-4 reset-filters" @click="resetFilters">
il y a peut etre un peu de style a cote a changer aussi dans `reset-filters` notamment 🤔

2021-04-09 09:49 UTC, KennyCallegari commented on src/core/mixins/courseFiltersMixin.js
> +        .sort((a, b) => a.label.localeCompare(b.label));
done

2021-04-09 13:27 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      cursor: pointer;
tu peux utiliser ce style grid pour les autres CoursesDirectory du coup et le mutuliser dans `courses.styl`

2021-04-09 13:27 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      <div class="col-xs-12 col-sm-6 col-md-4 reset-filters" @click="resetFilters">
done

2021-04-09 13:32 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +  .filters-container
tu l'as defini mais tu ne l'utilises pas

2021-04-09 13:42 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      <ni-select :class="{ 'q-pr-sm': $q.platform.is.desktop }" :options="companyFilterOptions"
et tu pourras enlever `:class` du coup 
et en dessous aussi

2021-04-09 13:48 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      cursor: pointer;
done

2021-04-09 13:49 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +  .filters-container
done

2021-04-09 13:50 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +      <ni-select :class="{ 'q-pr-sm': $q.platform.is.desktop }" :options="companyFilterOptions"
heu... j'ai dû me tromper du coup parce que je ne peux pas les enlever

2021-04-09 14:25 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
>          <span>Effacer les filtres</span>
je pense que tu n'as pass besoin du span en fait

2021-04-09 14:26 UTC, sophiemoustard requested changes

2021-04-09 14:26 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
>          <span>Effacer les filtres</span>
idem pour les autres

2021-04-09 14:26 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
>        </div>
a mettre dans la div `<div class="filters-container">`

2021-04-09 14:26 UTC, sophiemoustard commented on src/css/course.styl
> +      cursor: pointer;
suite a mon retour sur le span, pense a bouger ca

2021-04-09 14:32 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
>          <span>Effacer les filtres</span>
done

2021-04-09 14:33 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
>        </div>
je trouve ça moins beau, dis moi ce que tu en penses

2021-04-09 14:34 UTC, KennyCallegari commented on src/css/course.styl
> +      cursor: pointer;
done

2021-04-09 14:45 UTC, sophiemoustard approved these changes

2021-04-09 14:46 UTC, merged