Com 1978
sophiemoustard/alenvi-webapp pull request #1062
Opened 2021-04-09 15:19 UTC by KennyCallegari

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach / client_admin

- Cas d'usage : 
Si je clique sur une structure dans la liste des structures partenaires, je suis dirigé vers la page profile de celle ci, où je peux modifier les 4 champs d'une structure partenaire

2021-04-09 16:34 UTC, sophiemoustard commented on src/core/api/PartnerOrganizations.js
> +  async getById (partnerOrganizationId) {
tu pourrais l'appeler id pour que ce soit plus court et plus lisible ... comme c'est un getById et qu'on appelle la route `/partnerorganizations` on se doute que c'est partnerorganizationId ^^

2021-04-09 16:34 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +      :error-message="addressError($v.partnerOrganization)" />
pbm d'indentation

2021-04-09 16:35 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +  metaInfo: { title: 'Structure partenaire' },
je crois qu'on met plutot 'Fiche structure partenaire'

2021-04-09 16:44 UTC, sophiemoustard requested changes

2021-04-09 16:44 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +        if (e.status === 409) return NotifyWarning(e.data.message);
comment peux tu avoir une 409 du back ?

2021-04-09 16:44 UTC, sophiemoustard commented on src/core/api/PartnerOrganizations.js
> +  async updateById (partnerOrganizationId, payload) {
idem ici

2021-04-09 16:44 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +    <ni-profile-header :title="partnerOrganization.name" />
il faut que tu crées un data `partnerOrganizationName` pour que si on change le nom dans l'input, ca ne s'affiche en haut qu'une fois le changement validé par le back

2021-04-12 10:55 UTC, KennyCallegari commented on src/core/api/PartnerOrganizations.js
> +  async getById (partnerOrganizationId) {
done

2021-04-12 10:56 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +      :error-message="addressError($v.partnerOrganization)" />
done

2021-04-12 10:56 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +  metaInfo: { title: 'Structure partenaire' },
done

2021-04-12 10:57 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +        if (e.status === 409) return NotifyWarning(e.data.message);
Si le nom existe déjà

2021-04-12 10:57 UTC, KennyCallegari commented on src/core/api/PartnerOrganizations.js
> +  async updateById (partnerOrganizationId, payload) {
done

2021-04-12 11:04 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +    <ni-profile-header :title="partnerOrganization.name" />
done

2021-04-12 12:11 UTC, cmolle commented on src/core/api/PartnerOrganizations.js
> +    );
sur une ligne

2021-04-12 12:28 UTC, ulysseferreira commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +        NotifyPositive('Modification enregistrée');
il manque un point

2021-04-12 15:01 UTC, KennyCallegari commented on src/core/api/PartnerOrganizations.js
> +    );
done

2021-04-12 15:13 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +  async mounted () {
c'est plutot que `created` qu'on fait ca

2021-04-12 15:13 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +        NotifyPositive('Modification enregistrée');
done

2021-04-12 15:14 UTC, KennyCallegari commented on src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
> +  async mounted () {
done

2021-04-12 15:16 UTC, sophiemoustard approved these changes

2021-04-12 17:03 UTC, cmolle approved these changes

2021-04-12 17:04 UTC, merged