Com 2035
sophiemoustard/alenvi-webapp pull request #1085
Opened 2021-04-28 14:34 UTC by ulysseferreira

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : formateur / admin / rof

- Cas d'usage : j'ai accès aux réponses au questionnaire de recueil des attentes

2021-04-28 17:08 UTC, KennyCallegari commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +      <div class="q-ma-sm q-pa-xs text-center text-grey-800 bg-grey-300 answers">
ici je mettrais `q-my-sm` plutôt et je regrouperai` text-center text-grey-800 bg-grey-300` dans answers
Qu'en penses-tu ?

2021-04-29 10:25 UTC, KennyCallegari approved these changes

2021-04-29 12:26 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="questionnaires.length" class="q-my-lg">
tu pourrais ajouter un peux de marge en dessous `q-mb-xl` qu'en penses tu ?

2021-04-29 12:31 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="questionnaires.length" class="q-my-lg">
plus largement que pense tu de mettre `q-mb-xl` sur chaque bloc (Emargement / Quesstionnaire / Progression) plutot que les `q-my-...` et d'ajouter une `q-mt-md` sur le bloc emargement ?

2021-04-29 12:31 UTC, cmolle reviewed
Il y a une bordure autour des cartes sur figma

2021-04-29 12:31 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    width: 184px
normalement tu n'en as pas besoin puisque tu geres la largeur dans l'affichage grid

2021-04-29 12:31 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    width: 100px
idem

2021-04-29 12:32 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    margin 16px 0px;
tu peux le gerer avec un `q-my-md`

2021-04-29 12:32 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    padding: 8px
tu peux le gerer avec un `q-ma-sm` je crois

2021-04-29 12:34 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +      cursor: pointer
tu peux utiliser la classe `cursor-pointer`

2021-04-29 12:35 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
pourquoi important ?

2021-04-29 12:42 UTC, sophiemoustard requested changes

2021-04-29 12:42 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
idem

2021-04-29 12:42 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +        {{ formatQuantity('réponse',questionnaire.historiesCount) }}
il manque un espace apres la virgule

2021-04-29 12:42 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +  grid-template-columns: repeat(auto-fill, 184px)
que penses tu de le mettre une peu plus large genre 224px ; la je le trouve tout petit

2021-04-29 12:49 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
et peut on rester sur du 8px (idem pour l'autre) ?

2021-04-29 13:06 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="questionnaires.length" class="q-my-lg">
done

2021-04-29 13:16 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    width: 184px
done

2021-04-29 13:17 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    width: 100px
hum là c'est interne à la cellule, si je mets pas cette width ça prend toute la largeur et c'est pas comme ça sur le figma

2021-04-29 13:18 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    margin 16px 0px;
done

2021-04-29 13:18 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    padding: 8px
q-pa-sm plutôt non ?

2021-04-29 13:20 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
done

2021-04-29 13:20 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
done

2021-04-29 13:20 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +        {{ formatQuantity('réponse',questionnaire.historiesCount) }}
done

2021-04-29 13:22 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +  grid-template-columns: repeat(auto-fill, 184px)
done (c'est plus que sur le figma par contre)

2021-04-29 14:17 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="questionnaires.length" class="q-my-lg">
je pense que tu n'as pas compris mon commentaire : 
tu as mis `q-mb-xl` et `q-mt-md` sur questionnaires
et je te proposais de plutot mettre : 
- `q-mb-xl` sur sur chaque bloc (Emargement / Quesstionnaire / Progression) pour gerer l'ecart entre les blocs
- - `q-mt-md` seulement sur Emargement pour gerer l'espace en haut de l'onglet

2021-04-29 14:18 UTC, sophiemoustard commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
tu n'as pas fait le changement 8px

2021-04-29 14:19 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +  grid-template-columns: repeat(auto-fill, 184px)
yes j'ai vu mais je trouve le rendu un peu petit donc je challenge

2021-04-29 14:20 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
>  .answers
je ne vois aps ou cette classe est utlisée

2021-04-29 15:15 UTC, ulysseferreira commented on src/core/components/courses/QuestionnaireAnswersCell.vue
> +    border-radius: 10px !important
done

2021-04-29 15:22 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
>  .answers
done

2021-04-29 16:43 UTC, cmolle approved these changes

2021-04-30 07:36 UTC, KennyCallegari approved these changes

2021-04-30 07:45 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="questionnaires.length" class="q-my-lg">
done

2021-04-30 08:10 UTC, sophiemoustard approved these changes

2021-04-30 08:16 UTC, merged