COM-2109: inclusive
sophiemoustard/alenvi-webapp pull request #1201
Opened 2021-08-02 12:16 UTC by ulysseferreira

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : tous

- Périmetre roles : tous

- Cas d'usage : les appellations au singulier sont passées en inclusif (sûr(e), apprenant(e), formatrice, utilisatrice, le/la, administratrice, testeuse, etc.)
Il faut tester à peu près toute l'app pour s'assurer qu'il n'y a pas d'oubli et que les formules vous semblent adéquates

2021-08-02 13:18 UTC, CorentinMartinot reviewed
Sur une page formation, onglet "suivi des stagiaire". On melange les termes "participant", "stagiaire" et "apprenant". Je pense qu'on peut remplacer "apprenant" par "participant". T'en penses quoi ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error="validations.trainee.$error" @input="update($event, 'trainee')" in-modal caption="Apprenant(e)"
Participant(e) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/components/table/AttendanceTable.vue
> +        <div class="text-center text-italic">Aucun(e) apprenant(e) n'a été ajouté(e) à cette formation</div>
Aucun(e) participant(e) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
"non du/ de la participant(e)"

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/data/constants.js
> +  { label: 'Rupture période d’essai employeur(euse)', value: 'employer_trial_period_termination' },
tu mets utilisateur/utilisatrice au dessus et la tu met pas employeur/employeuse. C'est pas homogene

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/data/constants.js
> +  { label: 'Rupture période d’essai employeur(euse)', value: 'employer_trial_period_termination' },
perso je prefere utilisateur(ice) employeur(euse)

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/data/constants.js
> +  { label: 'Rupture période d’essai employeur(euse)', value: 'employer_trial_period_termination' },
perso je prefere utilisateur(ice) employeur(euse)

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice';
same. Selon ce que tu choisis pour ma question plus haut :soit c'est bien soit il faut Administrateur(ice)

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/mixins/learnerMixin.js
> +          return 'Formateur/formatrice';
pareil

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice Vendeur';
pareil

2021-08-02 13:50 UTC, CorentinMartinot commented on src/core/pages/signin/ForgotPassword.vue
> +            content = 'Aucun(e) utilisateur/utilisatrice ne correspond à l\'email indiqué';
pareil

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +      Ajouter une <span class="text-weight-bold">fiche aidant</span>
"d'une fiche" ou "d'une fiche aidant(e)", c du masculin generiaue

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/client/mixins/helperMixin.js
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
utilisateur(ice) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
>          'Bénéficiaire',
Financeur(euse) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/TesterTable.vue
> +          <ni-button color="primary" icon="add" label="Ajouter un(e) testeur/testeuse" :disable="loading"
testeur(euse) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
>          'Référent',
Référent(e)

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/TesterTable.vue
> +          NotifyPositive('Testeur/testeuse ajouté(e) avec succès.');
testeur(euse)

pareil pour tout le fichier ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/components/trainers/ProfileInfo.vue
> +      <ni-input caption="Biographie du formateur/de la formatrice" v-model="userProfile.biography" type="textarea"
du/ de la formateur(ice)

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/components/trainers/TrainerCreationModal.vue
> +      Créer une nouvelle<span class="text-weight-bold">fiche formateur</span>
"fiche ø" ou "fiche formateur(ice)" ou "fiche formateur/formatrice"

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
> +  metaInfo: { title: 'Fiche formateur/formatrice' },
formateur(ice) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
utilisateur(ice) ?

2021-08-02 13:50 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyPositive('Formateur/formatrice créé(e)');
formateur(ice) ?

pareil piur tout le fichier ?

2021-08-02 14:14 UTC, ulysseferreira commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error="validations.trainee.$error" @input="update($event, 'trainee')" in-modal caption="Apprenant(e)"
done

2021-08-02 14:14 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable.vue
> +        <div class="text-center text-italic">Aucun(e) apprenant(e) n'a été ajouté(e) à cette formation</div>
done

2021-08-02 14:15 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
done

2021-08-02 14:47 UTC, ulysseferreira commented on src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
>          'Référent',
done

2021-08-02 15:20 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +            else return NotifyNegative('Le/la stagiaire n\'est pas relié(e) à la structure de la formation.');
Cette personne ?
pour etre coherent avec le titre du bouton

2021-08-02 15:20 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +        NotifyNegative('Erreur lors de l\'ajout du/de la stagiaire.');
idem personne

2021-08-02 15:22 UTC, sophiemoustard commented on src/core/components/courses/CourseHistory.vue
> +        type: 'participant(e)',
stagiaire ? pour etre coherent avec les modales ?

2021-08-02 15:22 UTC, sophiemoustard commented on src/core/components/courses/CourseHistory.vue
>          infos: `\r\n${formatIdentity(this.courseHistory.trainee.identity, 'FL')}`,
idem ?

2021-08-02 15:22 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +        <div class="text-center text-italic">Aucun(e) apprenant(e) n'a été ajouté(e) à cette formation</div>
stagiaire pour etre coherent avec les modales et messages d'erreur ?

2021-08-02 15:23 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
On pourrait juste mettre `Participant(e)` non ?

2021-08-02 15:24 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +          return NotifyNegative('L\'utilisateur/utilisatrice n\'est pas relié(e) à cette structure.');
personne ?

2021-08-02 15:24 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +          return NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
idem ?

2021-08-02 15:24 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la création de l\'utilisateur/utilisatrice.');
idem ?

2021-08-02 15:24 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la création du/de la coach');
de la fiche coach ?

2021-08-02 15:25 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyPositive('Utilisateur/utilisatrice modifié(e).');
idem

2021-08-02 15:25 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la modification de l\'utilisateur/utilisatrice.');
idem

2021-08-02 15:25 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la récupération des utilisateurs.');
idem

2021-08-02 15:40 UTC, sophiemoustard requested changes

2021-08-02 15:40 UTC, sophiemoustard commented on src/core/components/table/TraineeAttendanceCreationModal.vue
> +         :inline="true" />
je pense que tu peux mettre `inline` uniquement

2021-08-02 15:40 UTC, sophiemoustard commented on src/core/data/constants.js
> +  { label: 'Rupture période d’essai employeur(euse)', value: 'employer_trial_period_termination' },
pour le coup, j'ai l'impression que la on parle plutot du concept de l'emploeyr que de la personne physique... donc je laisserait bien comme c'etait avant

2021-08-02 15:40 UTC, sophiemoustard commented on src/core/pages/signin/ForgotPassword.vue
> +            content = 'Aucun(e) utilisateur/utilisatrice ne correspond à l\'email indiqué';
Aucun compte ?

2021-08-02 15:40 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +        NotifyPositive('Utilisateur/utilisatrice enregistré(e).');
idem ?

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +      Ajouter une <span class="text-weight-bold">fiche aidant</span>
je suis plutot d'accord avec ec qu'a mis Ulysse pour le coup...

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/client/mixins/helperMixin.js
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
compte ? personne ?

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/client/components/table/CustomerNotesContainer.vue
> +    <div v-else class="text-italic text-center q-py-sm">Aucune note de suivi pour le/la bénéficiaire.</div>
Aucune note de suivi ? pour faire plus simple

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        NotifyNegative('Impossible de récupérer les évènements facturés de le/la bénéficiaire.');
du / de la

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
>          'Bénéficiaire',
pour le coup on peut garder Financeur car ce ne sont pas des personnes physique derriere mais des conseils departementaux

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/components/trainers/ProfileInfo.vue
> +      <ni-input caption="Biographie du formateur/de la formatrice" v-model="userProfile.biography" type="textarea"
Biographie ? pour s'epargner le souci

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/components/trainers/TrainerCreationModal.vue
> +      Créer une nouvelle<span class="text-weight-bold">fiche formateur</span>
idem je suis d'accord avec ce qu'a mis Ulysse

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
> +  metaInfo: { title: 'Fiche apprenant(e)' },
si tu mets `Creer une nouvelle fiche formateur` dnas la logique ici tu peux garder `Fiche apprenant` car apprenant ici est une categorie

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
> +  metaInfo: { title: 'Fiche formateur/formatrice' },
idem

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
personne ? compte ?

2021-08-02 15:40 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyPositive('Formateur/formatrice créé(e)');
compte ? idem pareil pour tout le fichier

2021-08-02 15:43 UTC, sophiemoustard commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice';
Admin ?

2021-08-02 16:11 UTC, ulysseferreira commented on src/core/components/courses/TraineeTable.vue
> +            else return NotifyNegative('Le/la stagiaire n\'est pas relié(e) à la structure de la formation.');
done

2021-08-02 16:18 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
Voire même Participants non ?

2021-08-02 16:19 UTC, ulysseferreira commented on src/core/data/constants.js
> +  { label: 'Rupture période d’essai employeur(euse)', value: 'employer_trial_period_termination' },
done

2021-08-02 16:20 UTC, ulysseferreira commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice';
ça fait pas un peu familier ?

2021-08-02 16:21 UTC, ulysseferreira commented on src/core/pages/signin/ForgotPassword.vue
> +            content = 'Aucun(e) utilisateur/utilisatrice ne correspond à l\'email indiqué';
done

2021-08-02 16:21 UTC, ulysseferreira commented on src/modules/client/mixins/helperMixin.js
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
done

2021-08-02 16:22 UTC, ulysseferreira commented on src/modules/vendor/components/trainers/ProfileInfo.vue
> +      <ni-input caption="Biographie du formateur/de la formatrice" v-model="userProfile.biography" type="textarea"
done

2021-08-02 16:24 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
> +  metaInfo: { title: 'Fiche formateur/formatrice' },
done

2021-08-02 16:24 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
done

2021-08-02 16:25 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +          NotifyPositive('Formateur/formatrice créé(e)');
done

2021-08-02 16:26 UTC, ulysseferreira commented on src/core/components/courses/CourseHistory.vue
> +        type: 'participant(e)',
done

2021-08-02 16:26 UTC, ulysseferreira commented on src/core/components/courses/CourseHistory.vue
>          infos: `\r\n${formatIdentity(this.courseHistory.trainee.identity, 'FL')}`,
done

2021-08-02 16:26 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +          return NotifyNegative('L\'utilisateur/utilisatrice n\'est pas relié(e) à cette structure.');
done

2021-08-02 16:28 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyPositive('Utilisateur/utilisatrice enregistré(e).');
done

2021-08-02 16:28 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +          return NotifyNegative('Utilisateur/utilisatrice déjà existant(e).');
done

2021-08-02 16:29 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la création de l\'utilisateur/utilisatrice.');
done

2021-08-02 16:29 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la création du/de la coach');
done

2021-08-02 16:29 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyPositive('Utilisateur/utilisatrice modifié(e).');
done

2021-08-02 16:29 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la modification de l\'utilisateur/utilisatrice.');
done

2021-08-02 16:29 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +        NotifyNegative('Erreur lors de la récupération des utilisateurs.');
done

2021-08-02 16:34 UTC, ulysseferreira commented on src/core/components/table/TraineeAttendanceCreationModal.vue
> +         :inline="true" />
done

2021-08-02 16:35 UTC, ulysseferreira commented on src/modules/client/components/table/CustomerNotesContainer.vue
> +    <div v-else class="text-italic text-center q-py-sm">Aucune note de suivi pour le/la bénéficiaire.</div>
done

2021-08-02 16:39 UTC, ulysseferreira commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        NotifyNegative('Impossible de récupérer les évènements facturés de le/la bénéficiaire.');
ou juste "impossible de récupérer les événements facturés" comme pour les notes de suivi ?

2021-08-02 16:39 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
> +  metaInfo: { title: 'Fiche apprenant(e)' },
done

2021-08-03 10:20 UTC, ulysseferreira commented on src/core/mixins/learnerMixin.js
> +          return 'Formateur/formatrice';
done

2021-08-03 10:21 UTC, ulysseferreira commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice Vendeur';
done

2021-08-03 10:21 UTC, ulysseferreira commented on src/modules/vendor/components/programs/TesterTable.vue
> +          <ni-button color="primary" icon="add" label="Ajouter un(e) testeur/testeuse" :disable="loading"
done

2021-08-03 10:21 UTC, ulysseferreira commented on src/modules/vendor/components/programs/TesterTable.vue
> +          NotifyPositive('Testeur/testeuse ajouté(e) avec succès.');
done

2021-08-03 10:49 UTC, CorentinMartinot commented on src/modules/vendor/components/trainers/TrainerCreationModal.vue
> +      Créer une nouvelle<span class="text-weight-bold">fiche formateur</span>
t'as oublié un espace entre nouvelle et fiche

2021-08-03 11:28 UTC, ulysseferreira commented on src/modules/vendor/components/trainers/TrainerCreationModal.vue
> +      Créer une nouvelle<span class="text-weight-bold">fiche formateur</span>
done

2021-08-03 11:31 UTC, CorentinMartinot commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
Je mettrai Participant(e), car c'est un titre de colonne. Au pluriel on pourrai penser que c'est un tableau de participants et non un tableau de feuille d'emargement

2021-08-03 11:39 UTC, CorentinMartinot commented on src/core/components/courses/LearnerCreationModal.vue
> +        Ajouter une <span class="text-weight-bold">fiche apprenant</span>
"fiche participant" non ?

2021-08-03 11:44 UTC, sophiemoustard commented on src/core/components/courses/LearnerCreationModal.vue
> +        Ajouter une <span class="text-weight-bold">fiche apprenant</span>
on parle de participant dans le cadre d'une formation mixte - sinon on parle d'apprenant de maniere general

2021-08-03 11:48 UTC, sophiemoustard reviewed
Je suis perdue entre participant / stagiaire / personne / apprenant. j'ai l'impression qu'on melange les 4

2021-08-03 11:49 UTC, sophiemoustard commented on src/core/mixins/learnerMixin.js
> +          return 'Administrateur/administratrice';
ou tu as raison

2021-08-03 11:53 UTC, ulysseferreira commented on src/core/components/courses/LearnerCreationModal.vue
> +        Ajouter une <span class="text-weight-bold">fiche apprenant</span>
sauf que là c'est la modale de création d'un apprenant, qui est aussi utilisée dans le répertoire apprenant donc on peut pas trop la changer celle-là

2021-08-03 11:54 UTC, CorentinMartinot commented on src/core/components/table/TraineeAttendanceCreationModal.vue
> +        type="checkbox" caption="Selectionner les créneaux auxquelles a été présent(e) le/la participant(e)" inline />
mauvaise indentation

2021-08-03 12:30 UTC, ulysseferreira commented on src/core/components/table/TraineeAttendanceCreationModal.vue
> +        type="checkbox" caption="Selectionner les créneaux auxquelles a été présent(e) le/la participant(e)" inline />
done

2021-08-03 12:32 UTC, CorentinMartinot reviewed
Sur une page formation >  onglet "organisation" > titre d'input : 

- intervenant => intervenant(e)
- referent compani => referent(e) compani

2021-08-03 12:37 UTC, sophiemoustard commented
Pour ce qui est de l'utlisation du terme "fiche" : 
- je propose qu'on l'utilise uniquement dans le cadre 
 --des bénéficiaires car comme il n'y a pas de compte derrière ça a du sens
 -- les metadata des pages
- pour aidant / auxiliaire / coach / apprenant / ..., on pourrait parler de `personne` ou `compte` selon les cas
qu'en penses tu ?

2021-08-03 13:17 UTC, CorentinMartinot approved these changes

2021-08-03 14:49 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Participants',
avec Corentin on penchait plus pour `Participant(e)`

2021-08-03 14:51 UTC, sophiemoustard commented on src/core/components/table/CoachCreationModal.vue
> +      Ajouter un <span class="text-weight-bold">compte</span>
dans les titre et bouton plus bas je mettrai plus `personne`

je mettrai plus compte dans les notify du genre `Compte deja existant` ou `Compte deja rattaché`

2021-08-03 14:51 UTC, sophiemoustard commented on src/core/components/table/CoachEditionModal.vue
> +      Éditer un <span class="text-weight-bold">compte</span>
idem

2021-08-03 14:51 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +      <p class="text-weight-bold">Comptes</p>
Coachs ?

2021-08-03 14:51 UTC, sophiemoustard commented on src/core/components/table/CoachList.vue
> +          <ni-button color="primary" icon="add" label="Ajouter un compte" @click="coachCreationModal = true"
une personne

2021-08-03 14:55 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Participants',
done

2021-08-03 14:58 UTC, ulysseferreira commented on src/core/components/table/CoachCreationModal.vue
> +      Ajouter un <span class="text-weight-bold">compte</span>
done

2021-08-03 14:59 UTC, sophiemoustard requested changes

2021-08-03 14:59 UTC, sophiemoustard commented on src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
> +      Créer un nouveau <span class="text-weight-bold">compte auxiliaire</span>
"Ajouter une personne" pour faire comme les autres modales ? idem pour le bouton ?

2021-08-03 14:59 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +    <q-btn class="fixed fab-custom" no-caps rounded color="primary" icon="add" label="Ajouter un compte"
ajouter une personne ?

2021-08-03 14:59 UTC, sophiemoustard commented on src/modules/vendor/components/trainers/TrainerCreationModal.vue
> +      Créer un nouveau <span class="text-weight-bold">compte formateur</span>
Ajouter une personne ?
idem pour le bouton

2021-08-03 15:00 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +      <p class="text-weight-bold">Comptes</p>
y a pas que des coachs, c'est pas gênant ?

2021-08-03 15:01 UTC, ulysseferreira commented on src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
> +      Créer un nouveau <span class="text-weight-bold">compte auxiliaire</span>
done

2021-08-03 15:01 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +    <q-btn class="fixed fab-custom" no-caps rounded color="primary" icon="add" label="Ajouter un compte"
done

2021-08-03 15:04 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable.vue
> +          label: 'Nom de l\'apprenant(e)',
done

2021-08-03 15:13 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +      <p class="text-weight-bold">Comptes</p>
done

2021-08-03 15:18 UTC, merged