OM-1429 mode creditNote modals in separate components
sophiemoustard/alenvi-webapp pull request #653
Opened 2020-08-26 08:16 UTC by CorentinMartinot

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : 

- Périmetre roles : 

- Cas d'usage : refacto modales des avoirs

2020-08-26 08:36 UTC, KennyCallegari commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +      :has-linked-events="hasLinkedEvents" :credit-note-events="creditNoteEvents" @loading="loading"
Pourquoi `@loading` et pas `:loading` ?

2020-08-26 08:38 UTC, CorentinMartinot commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +      :has-linked-events="hasLinkedEvents" :credit-note-events="creditNoteEvents" @loading="loading"
a oui merci :)

2020-08-26 13:33 UTC, sophiemoustard requested changes
quand j'arrive sur la page des avoirs, je ne vois rien

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        :error="validations.startDate.$error" @blur="validations.startDate.$touch" in-modal type="date"
il n'y a  pas de props `type` dans DateInput donc tu peux l'enlever - et en dessous pareil

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      :disable="thirdPartyPayerOptions.length === 0" clearable />
sur 2 lignes

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +            {{ formatPrice(newCreditNote.exclTaxesCustomer) }}
sur une ligne non ? et si oui ca passe pour les autres du coup

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      eventsNotFoundMessage: 'Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données',
tu peux le mettre directement dans le template

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +            :error="validations.events.$error" />
sur 2 lignes

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +              {{ formatPrice(editedCreditNote.exclTaxesCustomer) }}
idem

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +              {{ formatPrice(editedCreditNote.exclTaxesCustomer) }}
et en dessous

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +      eventsNotFoundMessage: 'Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données',
idem

2020-08-26 13:33 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +      :subscriptions-options="subscriptionsOptions" :credit-note-events-options="creditNoteEventsOptions"
il y a un souci d'indentation

2020-08-26 14:33 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +            :error="validations.events.$error" />
je crois pas que c'est possible

2020-08-26 14:34 UTC, CorentinMartinot commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +      :subscriptions-options="subscriptionsOptions" :credit-note-events-options="creditNoteEventsOptions"
doen

2020-08-26 14:34 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +      eventsNotFoundMessage: 'Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données',
done

2020-08-26 14:34 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +              {{ formatPrice(editedCreditNote.exclTaxesCustomer) }}
done

2020-08-26 14:35 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      eventsNotFoundMessage: 'Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données',
done

2020-08-26 14:35 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +            {{ formatPrice(newCreditNote.exclTaxesCustomer) }}
done

2020-08-26 14:36 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      :disable="thirdPartyPayerOptions.length === 0" clearable />
done

2020-08-26 14:36 UTC, CorentinMartinot commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        :error="validations.startDate.$error" @blur="validations.startDate.$touch" in-modal type="date"
done

2020-08-26 14:52 UTC, sophiemoustard requested changes

2020-08-26 14:52 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        <p>Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données</p>
tu n'as pas besoin du \ du coup

2020-08-26 14:52 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +          <p>Il n\'y a aucune intervention facturée pour le bénéficiaire aux dates données</p>
idem

2020-08-26 16:24 UTC, cmolle approved these changes

2020-08-27 11:54 UTC, KennyCallegari approved these changes

2020-08-27 13:07 UTC, sophiemoustard approved these changes

2020-08-27 13:11 UTC, merged