Com 1429 reuse
sophiemoustard/alenvi-webapp pull request #658
Opened 2020-08-27 11:47 UTC by CorentinMartinot

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : admin

- Cas d'usage : je peux reutiliser/dupliquer une activité

2020-08-27 14:13 UTC, sophiemoustard requested changes

2020-08-27 14:13 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +      } catch (e) {
this.programs = []

2020-08-28 07:02 UTC, sophiemoustard requested changes

2020-08-28 07:02 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +          .flat(2)
a quoi te sert ton flat(2) ?

2020-08-28 07:02 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +      } catch (e) {
this.activityOptions = []

2020-08-28 07:07 UTC, sophiemoustard requested changes
ce serait mieux que le radio soit toujours a gauche qu'en penses tu ?
![image](https://user-images.githubusercontent.com/24521863/91531920-d83dd900-e90d-11ea-8d35-22f79fc38a37.png)

2020-08-28 07:07 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +            icon-right="add" @click="submitReuse" />
flat sur tes boutons

2020-08-28 07:08 UTC, sophiemoustard requested changes

2020-08-28 07:08 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +        <div class="buttons q-ma-lg">
plutot  q-ma-md

2020-08-28 07:08 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +          <q-btn class="q-mr-xs" no-caps label="Dupliquer l'activité" color="primary" :loading="loading"
pourquoi tu mets cette marge ?
idem pour en dessous ?

2020-08-28 09:17 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +            icon-right="add" @click="submitReuse" />
Les boutons ne sont pas dans le bon ordre + il n'y a pas de '+' sur les bouton du Figma.

2020-08-28 09:17 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +            icon-right="add" @click="submitReuse" />
Et il ne faut pas centrer la liste mais la coller à gauche

2020-08-31 08:10 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        this.reusedActivity = value;
done

2020-08-31 08:10 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        this.reusedActivity = value;
done

2020-08-31 08:10 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    this.refreshPrograms();
done

2020-08-31 08:10 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ProfileContent.vue
> +      } catch (e) {
done

2020-08-31 08:16 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +        <div class="buttons q-ma-lg">
done

2020-08-31 08:19 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +          <q-btn class="q-mr-xs" no-caps label="Dupliquer l'activité" color="primary" :loading="loading"
done

2020-08-31 08:19 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +      } catch (e) {
doen

2020-08-31 08:54 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +            icon-right="add" @click="submitReuse" />
done

2020-08-31 08:54 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +          .flat(2)
vu ensemble

2020-08-31 08:55 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ActivityReuseModal.vue
> +            icon-right="add" @click="submitReuse" />
done

2020-08-31 13:32 UTC, sophiemoustard approved these changes

2020-08-31 13:33 UTC, KennyCallegari approved these changes

2020-08-31 13:35 UTC, cmolle approved these changes

2020-08-31 13:51 UTC, merged