COM-1426 can detach steps from subprogram
sophiemoustard/alenvi-webapp pull request #659
Opened 2020-08-27 14:37 UTC by cmolle

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : admin/rof

- Cas d'usage : Je peux detacher une etape d'un sous programme

2020-08-27 16:03 UTC, KennyCallegari approved these changes

2020-08-27 16:03 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    validateStepDetachment (subProgramId, stepId) {
openValidateStepDetachmentDialog ?

2020-08-28 07:15 UTC, sophiemoustard requested changes

2020-08-28 07:15 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        NotifyPositive('Étape supprimée.');
pas supprimée mais retirée

2020-08-28 07:15 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        NotifyNegative('Erreur lors de la suppression de l\'étape.');
idem

2020-08-28 07:15 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    validateStepDetachment (subProgramId, stepId) {
par convention on est plutot parti sur du `validate` pour cette action la

2020-08-28 07:19 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    validateStepDetachment (subProgramId, stepId) {
ça marche !

2020-08-28 12:48 UTC, sophiemoustard approved these changes

2020-08-28 12:50 UTC, merged