Com 1437
sophiemoustard/alenvi-webapp pull request #666
Opened 2020-08-31 13:50 UTC by CorentinMartinot

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : admin rof

- Cas d'usage : retrait d'une activité

2020-08-31 15:03 UTC, sophiemoustard requested changes

2020-08-31 15:03 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        .onCancel(() => NotifyPositive('Retrait annulée.'));
pas de e dans annulé

2020-08-31 15:26 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        .onCancel(() => NotifyPositive('Retrait annulée.'));
done

2020-09-01 11:01 UTC, sophiemoustard approved these changes

2020-09-01 11:08 UTC, KennyCallegari approved these changes

2020-09-01 15:00 UTC, merged