Com 1430
sophiemoustard/alenvi-webapp pull request #673
Opened 2020-09-02 17:16 UTC by CorentinMartinot

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : admin rof

- Cas d'usage : je veux avoir un garde fou sur l'edition d'une activité réutilisé ailleurs

2020-09-03 08:20 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/CardContainer.vue
> +        <div class="card-cell cursor-pointer"
Sur une ligne ?

2020-09-03 08:20 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/CardContainer.vue
> +            <q-icon v-if="disableEdition" name="lock" size="xs" :class="{'locked-unselected': !isSelected(card)}" />
Tu n’utilises pas ni-button pour ça ?

2020-09-03 09:11 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/cards/CardContainer.vue
> +            <q-icon v-if="disableEdition" name="lock" size="xs" :class="{'locked-unselected': !isSelected(card)}" />
vu ensemble

2020-09-03 10:24 UTC, sophiemoustard requested changes

2020-09-03 10:40 UTC, cmolle commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +    validateUnlockEdition () {
Il manque une partie dans la message `Es-tu sûr(e) de vouloir déverrouiller cette activité ?`
Comme on met le nom du programme est-ce qu'il ne faudrait pas filtrer pour qu'il n'y ait qu'une fois chaque programme ? (dans le cas ou l'activité est utilisé dans plusieurs sous programme du meme programme)

2020-09-03 10:54 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +  async mounted () {
done

2020-09-03 10:56 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +    validateUnlockEdition () {
la partie ``es-tu sûr(e) de vouloir déverrouiller cette activité ?`` je l'ai mise a la fin du msg (par coherence avec d'autre qDialog avec un long msg

2020-09-03 12:06 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +    validateUnlockEdition () {
done + un filtre sur le programme de l'etape courant.

On est tou.te.s d'accord avec Sophie et Romain. Sauf que le qDialog n'accepte pas les \n :'(

2020-09-03 13:14 UTC, cmolle approved these changes

2020-09-03 14:17 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +    validateUnlockEdition () {
https://quasar.dev/quasar-plugins/dialog#Using-HTML

2020-09-03 15:05 UTC, cmolle approved these changes

2020-09-03 15:26 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +        html: true,
https://quasar.dev/quasar-plugins/dialog#Using-HTML

2020-09-04 07:15 UTC, sophiemoustard approved these changes

2020-09-04 07:18 UTC, merged