COM-1527
sophiemoustard/alenvi-webapp pull request #727
Opened 2020-10-07 11:33 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : VENDOR

- Périmetre roles : admin / rof

- Cas d'usage : 
Affiche un dot orange si une des carte de l'activité est incomplète
Affiche un dot vert + publiée si l'activité est publiée

2020-10-07 13:11 UTC, sophiemoustard requested changes

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +.stepOrActivityDotContainer
idem

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +.stepOrActivityPublishedText
idem

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          <span class="subProgramPublished" v-if="isPublished(subProgram)">Publié</span>
les class sont a mettre en kebab-case plutot

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          <span class="subProgramPublished" v-if="isPublished(subProgram)">Publié</span>
et je mettrais plutot `published-sub-program` qu'en penses tu ?

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div class="stepOrActivityDotContainer">
dot-container ?

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +.stepOrActivityPublishedText
published-text ?

2020-10-07 13:11 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    isActivityValid (activity) {
je ne suis pas sure qu'on ait besoin de cette fonction non ? on pourrait directement mettre `activity.areCardsValid` ?

2020-10-07 13:22 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    isActivityValid (activity) {
oui, c'était pour reprendre la logique de isPublished

2020-10-07 13:31 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +.stepOrActivityPublishedText
done

2020-10-07 13:31 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          <span class="subProgramPublished" v-if="isPublished(subProgram)">Publié</span>
done

2020-10-07 13:31 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div class="stepOrActivityDotContainer">
done

2020-10-07 13:31 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +.stepOrActivityDotContainer
done

2020-10-07 13:33 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +    isActivityValid (activity) {
done

2020-10-07 15:22 UTC, sophiemoustard commented
a confirmer avec Romain : je pense que ce serait mieux que ce soit aligné

2020-10-07 16:06 UTC, sophiemoustard approved these changes

2020-10-08 09:21 UTC, felix-commits approved these changes

2020-10-08 09:37 UTC, felix-commits reviewed
a voir avec Romain : peut-être mettre le label _publié_ en orange dans le cas d'une publication d'activité  partielle/incomplète
<img width="105" alt="Capture d’écran 2020-10-08 à 11 34 37" src="https://user-images.githubusercontent.com/70573684/95441580-95364300-095a-11eb-8c92-6ace87b04a0f.png">

2020-10-08 09:38 UTC, felix-commits commented
> a voir avec Romain : peut-être mettre le label _publié_ en orange dans le cas d'une publication d'activité partielle/incomplète
> <img alt="Capture d’écran 2020-10-08 à 11 34 37" width="105" src="https://user-images.githubusercontent.com/70573684/95441580-95364300-095a-11eb-8c92-6ace87b04a0f.png">

ca serait juste pour harmoniser avec le dot orange juste a cote

2020-10-09 08:10 UTC, merged