COM-1528 - Add step status dot
sophiemoustard/alenvi-webapp pull request #728
Opened 2020-10-07 15:35 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : VENDOR

- Périmetre roles : admin / rof

- Cas d'usage : 
Si mon step à des activités incomplètes -> pastille jaune
s'il est publié -> pastille verte + publié

2020-10-08 10:22 UTC, felix-commits approved these changes

2020-10-09 08:30 UTC, sophiemoustard requested changes

2020-10-09 08:30 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.type==='e_learning'" class="dot dot-error" />
utilise la constante

2020-10-09 08:30 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <q-icon v-if="step.areActivitiesValid && isPublished(step) && step.type==='e_learning'" size="12px"
idem

2020-10-09 08:30 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.type==='e_learning'" class="dot dot-error" />
mais d'ailleurs pourquoi cette condition ?

2020-10-09 08:30 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +  &-published
pourquoi cette nouvelle classe, egale a l'autre ?

2020-10-09 08:38 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.type==='e_learning'" class="dot dot-error" />
Sinon on affiche des dot sur les step on site.
Et je vois mal ce que ça indique le fait que tu n'aies pas rempli les cartes d'un step on site 😄

2020-10-09 08:40 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +  &-published
.dot est une classe de icon.styl
pour dot-published, je ne veux pas des autres conditions de .dot

2020-10-09 08:46 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.type==='e_learning'" class="dot dot-error" />
on pourra avoir ces quiz de pre-formation ou des questionnaire de satisfaction post formation pour less formations présentielles donc on aura aussi activités / cartes

2020-10-09 08:47 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.type==='e_learning'" class="dot dot-error" />
D'ailleurs je viens de voir qu'on peut avoir des activités avec des cartes dans les step on site

2020-10-09 09:23 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                    <div v-if="!step.areActivitiesValid && step.activities.length > 0" class="dot dot-error" />
dans le back je renverrai bien true pour `areActivitiesValid` si il n'y a pas d'activité
idem pour areCardsValid 
qu'en penses tu ?

2020-10-09 10:05 UTC, sophiemoustard approved these changes

2020-10-09 10:32 UTC, merged