COM-1571 refacto EstablishmentCreationModal
sophiemoustard/alenvi-webapp pull request #729
Opened 2020-10-08 14:16 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : nouveau composant _EstablishmentCreationModal_

(situé dans le même répertoire que le composant parent)

2020-10-08 14:24 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +      :establishment-urssaf-code-error="establishmentUrssafCodeError($v.newEstablishment)" />
ça fait beaucoup de props 😄 
Pourquoi ne pas avoir copié les fonctions dans establishementCreationModal ?
Tu pourrais aussi créer un objet avec tous les labels des erreurs et passer uniquement ça en props.

Qu'en penses-tu ?

2020-10-08 14:36 UTC, felix-commits commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +      :establishment-urssaf-code-error="establishmentUrssafCodeError($v.newEstablishment)" />
oui en effet, mais les fonctions sont partagées avec _EstablishmentEditionModal_ je vais essayer la 2e option !
ou sinon dans les mixins ca pourrait le faire?

2020-10-08 14:42 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +      :establishment-urssaf-code-error="establishmentUrssafCodeError($v.newEstablishment)" />
Je crois qu'on essaye de ne plus trop utiliser les mixins. Il faudrait demander à Chloé ou Sophie, perso je suis pas trop calé dessus

2020-10-08 15:10 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +      :establishment-urssaf-code-error="establishmentUrssafCodeError($v.newEstablishment)" />
wow je suis d'accord, ca fait beaucoup ^^
je suis assez partante pour faire une mixin

2020-10-08 15:44 UTC, KennyCallegari approved these changes

2020-10-09 06:37 UTC, sophiemoustard requested changes

2020-10-09 06:37 UTC, sophiemoustard commented on src/core/mixins/companyMixin.js
> +    },
a mettre dans un nouveau fichier establishmentMixin plutot

2020-10-09 09:46 UTC, felix-commits commented on src/core/mixins/companyMixin.js
> +    },
done!

2020-10-09 09:56 UTC, sophiemoustard approved these changes

2020-10-09 10:01 UTC, merged