COM-1549 - change otherFees to phoneFees
sophiemoustard/alenvi-webapp pull request #732
Opened 2020-10-09 15:39 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : CLIENT

- Périmetre roles : admin

- Cas d'usage : 
Dans les paies (stc et paie mensuelle), le champ 'autre frais' est devenu 'frais téléphonique'. Si l'auxiliaire à un justificatif de téléphone, les frais sont calculés, sinon ils sont de 0.

2020-10-12 09:58 UTC, cmolle approved these changes

2020-10-12 10:14 UTC, felix-commits approved these changes

2020-10-12 10:37 UTC, sophiemoustard commented on src/modules/client/mixins/payMixin.js
> +          label: 'Frais téléphoniques',
"Frais tél" plutot > ca ne sert a rien que le nom de la colonne prenne trop de place

2020-10-12 10:37 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/RhConfig.vue
> +          phoneFeeAmount: { required, positiveNumber, maxValue: maxValue(999) },
par rapport a maxValue, tu peux modifier `nbrError` dans configMixin pour que ca prenne en compte ce cas la stp ?
aujourd'hui si on met un nombre trop grand, ca met "Champ requis" en erreur

2020-10-12 10:37 UTC, sophiemoustard commented on src/modules/client/pages/ni/pay/ToPay.vue
> +        { label: 'Frais téléphoniques', value: 'phoneFees' },
le tri ne semble pas fonctionné... tu peux regarder stp ?

2020-10-12 14:02 UTC, KennyCallegari commented on src/modules/client/pages/ni/pay/ToPay.vue
> +        { label: 'Frais téléphoniques', value: 'phoneFees' },
done sur cette PR : https://github.com/sophiemoustard/alenvi-webapp/pull/735

2020-10-12 14:02 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/RhConfig.vue
> +          phoneFeeAmount: { required, positiveNumber, maxValue: maxValue(999) },
done

2020-10-12 14:02 UTC, KennyCallegari commented on src/modules/client/mixins/payMixin.js
> +          label: 'Frais téléphoniques',
done

2020-10-12 16:21 UTC, sophiemoustard commented on src/modules/client/mixins/configMixin.js
> +      if (get(this.$v, path).maxValue === false) return 'Le montant doit être inférieur à 999';
le 999 est un paraemetre qu'on passse a la fonction donc tu ne peux pas le mettre en dur comme ca ; sachant aussi que cette methode est utilisée dans plusiuers cas...
je renverai juste `Nombre non valide` comme au dessus

2020-10-12 16:21 UTC, sophiemoustard requested changes

2020-10-12 16:21 UTC, sophiemoustard commented on src/modules/client/mixins/payMixin.js
> +          label: 'Frais tel',
avec un accent

2020-10-13 06:46 UTC, sophiemoustard commented on src/modules/client/mixins/payMixin.js
> +        'Frais tel',
ici tu peux laisser téléphonique car on n'a pas de souci de place dans le tableau

2020-10-13 06:46 UTC, sophiemoustard commented on src/modules/client/pages/ni/pay/ToPay.vue
> +        { label: 'Frais tel', value: 'phoneFees' },
idem

2020-10-13 10:12 UTC, sophiemoustard approved these changes

2020-10-13 10:12 UTC, merged