COM-1527 - Add published dot to ActivityProfile after Romain's review
sophiemoustard/alenvi-webapp pull request #738
Opened 2020-10-14 13:41 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : VENDOR

- Périmetre roles : admin / rof

- Cas d'usage : 
Ajout du dot publié sur ActivityProfile (la page qui détaille les cartes des activités)
cf commentaire de Romain sous le ticket

2020-10-14 14:53 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +          </div>
plutot que de copier/coller ce code a 3 endroits on peu l'exporter dans un composant qu'en penses tu ?

2020-10-14 14:59 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +          </div>
J'y ai pensé, c'est pas exactement le même ici (au niveau du css).
Mais bon, je vais me débrouiller et te fais ça de suite

2020-10-14 16:39 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +          </div>
done

2020-10-15 07:36 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +    margin: 0 19px 0 3px
c'est a enlever ?

2020-10-15 12:43 UTC, sophiemoustard requested changes

2020-10-15 12:43 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                      :status="!activity.areCardsValid || activity.cards.length === 0
a mettre dans computed ?

2020-10-15 12:43 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +              <q-icon size="xs" :name="info.icon"
il manque une indentation

2020-10-15 12:43 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +          status: !this.isActivityValid ? PUBLISHED_DOT_WARNING : PUBLISHED_DOT_ACTIVE });
plutot que de passer le status tu pourrais passer la classe directement qu;en penses tu ?

2020-10-15 12:44 UTC, sophiemoustard commented
ca fait un dot un peu gros du coup ... tu peux valider avec ROmain si ca lui va ou non ? et on avise
<img width="233" alt="image" src="https://user-images.githubusercontent.com/24521863/96127878-df886880-0ef4-11eb-9960-3f3459180fef.png">

2020-10-15 12:59 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +                      :status="!activity.areCardsValid || activity.cards.length === 0
Dans methods plutôt non ?
On ne peut pas accéder à activity et step dans computed non ?

2020-10-15 13:07 UTC, KennyCallegari commented
> ca fait un dot un peu gros du coup ... tu peux valider avec ROmain si ca lui va ou non ? et on avise
> <img alt="image" width="233" src="https://user-images.githubusercontent.com/24521863/96127878-df886880-0ef4-11eb-9960-3f3459180fef.png">

![image](https://user-images.githubusercontent.com/45166809/96130378-23c93800-0ef8-11eb-89b1-e16a83f85efc.png)

2020-10-15 13:08 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +              <q-icon size="xs" :name="info.icon"
done

2020-10-15 13:11 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/config/ActivityProfile.vue
> +          status: !this.isActivityValid ? PUBLISHED_DOT_WARNING : PUBLISHED_DOT_ACTIVE });
done

2020-10-15 13:26 UTC, sophiemoustard approved these changes

2020-10-15 13:26 UTC, merged