Com 1597 - Refacto Rh Config Modals
sophiemoustard/alenvi-webapp pull request #743
Opened 2020-10-16 12:58 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : Client

- Périmetre roles : RH / admin

- Cas d'usage : 
Refacto des modals : NewInternalHourModal, AdministrativeDocumentCreationModal, SectorCreationModal et SectorEditionModal.

2020-10-16 13:39 UTC, sophiemoustard requested changes

2020-10-16 13:39 UTC, sophiemoustard commented on src/modules/client/components/config/NewInternalHourModal.vue
> +<template>
cf nos standards de nommage : InternalHourCreationModal pour le nom du fichier

2020-10-16 13:39 UTC, sophiemoustard commented on src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
> +    <ni-modal :value="value" @hide="hide">
en pluss de value, il vaut que tu @input pour emettre input (cf la pr de Felix) pour mettre a jour la value et ne pas le faire dans le `reset`

idem pour les autress modales

2020-10-16 14:03 UTC, KennyCallegari commented on src/modules/client/components/config/NewInternalHourModal.vue
> +<template>
done
Par contre les standards je ne vois pas où ils sont. Pour moi c'était le nom du v-model qu'on passait

2020-10-16 15:10 UTC, felix-commits approved these changes

2020-10-16 15:10 UTC, felix-commits commented on src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
> +  name: 'AdministrativeDocumentModal',
peut-être plutot `AdministrativeDocumentCreationModal`

2020-10-16 15:49 UTC, KennyCallegari commented on src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
> +  name: 'AdministrativeDocumentModal',
done

2020-10-16 15:49 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/RhConfig.vue
> +    <internal-hour-creation-modal v-model="newInternalHourModal" :validations="$v.newInternalHour"
Est-ce que `InternalHourCreationModal` ne serait pas plus pertinent comme v-model ?
@sophiemoustard @cmolle

2020-10-16 15:51 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/RhConfig.vue
> +    <internal-hour-creation-modal v-model="newInternalHourModal" :validations="$v.newInternalHour"
oui ! tu peux faire la refacto ? :)

2020-10-16 16:06 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/RhConfig.vue
> +      this.internalHourCreationModal = false;
cf ce qu'on s'est dit : a enlever 
plus bas aussi 
et gloablement : c'est a enlever dans tous les methodes reset reliées a des @hide

2020-10-19 07:25 UTC, sophiemoustard approved these changes

2020-10-19 07:25 UTC, merged