COM-1606 using rounded divs instead of q-linear-progress
sophiemoustard/alenvi-webapp pull request #774
Opened 2020-10-29 12:37 UTC by felix-commits

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : rof / admin

- Cas d'usage : affichage des sondages

version préliminaire: l'affichage mobile n'est pas géré, la taille du `surveyChart` est pour l'instant fixée manuellement a `304px`, j'utilise une prop `:style` (peut-on faire autrement?)

2020-10-29 13:13 UTC, KennyCallegari commented on src/core/components/courses/SurveyChart.vue
> +          <div class="bar-fill rounded-borders" :style="`height: ${line.percentage*100}%`" />
`index + 1`
et
`line.percentage * 100`

2020-10-29 13:49 UTC, KennyCallegari reviewed
![image](https://user-images.githubusercontent.com/45166809/97582389-f8fdda00-19f5-11eb-8caa-32d51535f879.png)

2020-10-29 13:49 UTC, KennyCallegari commented on src/core/components/courses/SurveyChart.vue
> +      <div>Très satisfait</div>
Il faut reprendre les label de la carte, non ?

2020-10-29 15:31 UTC, felix-commits commented on src/core/components/courses/SurveyChart.vue
> +          <div class="bar-fill rounded-borders" :style="`height: ${line.percentage*100}%`" />
done

2020-10-29 15:31 UTC, felix-commits commented on src/core/components/courses/SurveyChart.vue
> +      <div>Très satisfait</div>
tout a fait merci haha

2020-10-29 16:05 UTC, sophiemoustard requested changes

2020-10-29 16:05 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
> +  width: 304px
tu n'en as plus besoin

2020-10-29 16:05 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
> +  width: 48px
width: 100% plutot ()ca prend la largeur de la div parent

2020-10-29 16:05 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
> +  z-index: 2
en as tu besoin ?

2020-10-29 16:05 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
> +        <div class="percentage">{{ formatPercentage(line.percentage) }}</div>
pour ici en terme de fonctionnement tu peux faire comme suit : 
- la div `bar` est le container principale de ta barre et porte le fond beige claire
- a l'interieur tu as deux element en position absolute : 
   - qui part du bas (bottom: 0) la div `bar-fill` dont la taille est reliée au pourcentage 
   - fixer en haut (top : 0), un div qui porte le label 

ca implique quelques changements en plus aussi:
- tu peux mettre le fond beige claire + height 320px sur la classe `bar` et du coup tu n'as plus besoin de le mettre du `bar-label`
- tu passer la div qui porte {{ index + 1 }} en dessous de l'autre pour qu'elle s'affiche au dessus
- tu enlèves la margin top
- puisque `bar-fill` est en position absolute, il faut aussi que tu ajoutes une `width: 100%`

2020-10-29 16:10 UTC, felix-commits commented on src/core/components/courses/SurveyChart.vue
> +  z-index: 2
je crois car a 100% le bar fill passe devant les numeros

2020-10-29 16:12 UTC, felix-commits commented on src/core/components/courses/SurveyChart.vue
> +  z-index: 2
je vais passer la div en dessous plutot comme tu dis plus bas

2020-10-30 10:38 UTC, sophiemoustard requested changes

2020-10-30 10:38 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
> +  z-index: 2
l'element ne se voit pas quand on est a 100% : il est en dessous du fond beige foncé
il faut que tu passes `.bar-label` en `position: absolute` + `width: 100%` et que tu enleves le z-index et c;est bon

2020-10-30 10:39 UTC, sophiemoustard commented on src/core/components/courses/SurveyChart.vue
>    color: $middle-beige
up

2020-10-30 10:43 UTC, sophiemoustard reviewed
pour l'affichage mobile tu peux ajouter : 
```
@media screen and (max-width: 767px)
    width: 100%
```
sur `.bar-container` et `chart-footer` pour que le graphe prenne toute la largeur

et reduire aussi la largeur des barres .bar
```
@media screen and (max-width: 767px)
    width: 32px
```

2020-10-30 11:12 UTC, felix-commits commented
> @media screen and (max-width: 767px)
>     width: 32px

merci bcp

2020-10-30 12:35 UTC, sophiemoustard approved these changes

2020-10-30 12:40 UTC, KennyCallegari commented on src/core/components/courses/SurveyChart.vue
> +
A supprimer

2020-10-30 12:45 UTC, felix-commits commented on src/core/components/courses/SurveyChart.vue
> +
done

2020-10-30 12:54 UTC, KennyCallegari approved these changes

2020-10-30 12:55 UTC, merged