Com 1617
sophiemoustard/alenvi-webapp pull request #778
Opened 2020-11-02 17:30 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : VENDOR

- Périmetre roles : ROF / ADMIN

- Cas d'usage : 
Impossible de publier 2 sous programmes e learning dans le même programme

2020-11-02 17:39 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
Le ticket ne précise pas de validation front.
Qu'en pensez vous, il en faut une ?

2020-11-03 11:45 UTC, sophiemoustard requested changes

2020-11-03 11:45 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
gere plutot ca cas en te basant sur le code d'erreur

2020-11-03 11:45 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
oui tu peux 
comme tu es sur la page de programme, tu as tout ces sous programmes et donc tu peux regarder s'il a deja un sous-programme 100% eLearning de publié et bloquer la publication pour les autres sous-programmes 100% eLearning

tu peux te baser sur le virtual que je te propose en back du coup

2020-11-03 11:47 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
oui tu peux
comme tu es sur la page de programme, tu as tout ces sous programmes et donc tu peux regarder s'il a deja un sous-programme 100% eLearning de publié et bloquer la publication pour les autres sous-programmes 100% eLearning

tu peux te baser sur le virtual que je te propose en back du coup

2020-11-03 14:41 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
done

2020-11-03 14:41 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
Au final je l'ai enlevé, on le laisse même avec la validation front ?

2020-11-03 16:53 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
oui il vaut mieux

2020-11-04 13:12 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        if (e.data.message === 'Un sous-programme ELearning publié existe déjà') {
done

2020-11-04 13:29 UTC, sophiemoustard approved these changes

2020-11-04 18:35 UTC, merged