Com 1630
sophiemoustard/alenvi-webapp pull request #800
Opened 2020-11-16 15:22 UTC by felix-commits

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : 

- Périmetre roles : 

- Cas d'usage : 

NOTE 1: laffichage du learnersDirectory avec la colonne supplementaire nest pas optimal sur mobile (il faut scroller de gauche a droite)

NOTE 2: si je clique sur une formation d'un apprenant coté client je suis redirigé coté vendeur (car jai aussi un role vendeur, sinon 404)

2020-11-16 19:17 UTC, sophiemoustard requested changes

2020-11-16 19:17 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/LearnerProfile.vue
> +    getRoleLabel (role) {
tu pourrais creer une mixin `learnerMixin` et mettre ca dedans pour eviter le copier coler

2020-11-16 19:17 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/LearnerProfile.vue
> +      const infos = [{ icon: 'apartment', label: this.userProfile.company ? this.userProfile.company.name : 'N/A' }];
pas besoin de mettre la structure ici puisqu'on est coté client, c'est forcement la meme structure que la personne connectée

2020-11-16 19:17 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/LearnerProfile.vue
> +      return get(this.userProfile, 'role.client.name') || get(this.userProfile, 'role.vendor.name') || '';
comme on est coté client, on ne veut que son role client

2020-11-16 19:17 UTC, sophiemoustard commented on src/core/components/learners/ProfileHeader.vue
> +<template>
pourquoi avoir creer un nouveau composant ? tu peux tout simplement deplacer celui qui est dans `/modules/vendor/components/` et le mettre dans `core/components`

2020-11-16 19:17 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
>            format: value => value.subProgram.program.name + (value.misc ? ` - ${value.misc}` : ''),
peut etre utiliser get de lodash pour acceder a name dans `value.subProgram.program.name` on ne sait jamais

2020-11-16 19:17 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +          sort: (a, b) => sortStrings(a.subProgram.program.name, b.subProgram.program.name),
idem

2020-11-17 09:02 UTC, felix-commits commented
merci pour les retours, petite question du coup, sur jira il etait précisé de réutilier `ProfileCourse` pour qu'il soit partagé pour vendeur et client, pour prendre en compte tes retours est-ce que je le dupliquerai pas plutot ?

2020-11-17 10:54 UTC, felix-commits commented on src/modules/client/pages/ni/courses/LearnerProfile.vue
> +    getRoleLabel (role) {
done

2020-11-17 11:03 UTC, sophiemoustard requested changes

2020-11-17 11:29 UTC, sophiemoustard approved these changes

2020-11-17 11:32 UTC, felix-commits commented on src/core/mixins/learnerMixin.js
> +  },
done

2020-11-17 11:38 UTC, KennyCallegari approved these changes

2020-11-17 11:38 UTC, merged