Com 1633 - ELearningCourseProfile
sophiemoustard/alenvi-webapp pull request #801
Opened 2020-11-16 18:43 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage :
Lorsque je clique sur une formation eLearning dans la liste, je vois la page d'info sur cette formation contenant la liste des apprenants ainsi que leur progression.

PAS ENCORE FAIT :
- Le composant pour visualiser la progression
- Le sort() de la liste

2020-11-16 19:33 UTC, sophiemoustard requested changes

2020-11-16 19:33 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/TextMedia.vue
> +      card: { text: { required }, media: { publicId: required, link: required, type: required } },
tu peux mettre media a la ligne stp ? c'est comme ca qu'on formate les objets

2020-11-16 19:33 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    <ni-profile-header title="ICI LE TITRE DE LA COURSE" />
oups a corriger

2020-11-16 19:33 UTC, sophiemoustard commented on src/modules/vendor/router/routes.js
> +          // parent: 'management' à ajouter ?
ou car c'est une route qui appartient au menu `management` mais pass contre tu peux bien placer cette route juste en dessous de la route `ni/management/elearning-courses` c'est mieux si tout est regroupée

2020-11-16 19:33 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +          style: 'min-width: 200px; width: 70%',
tu peux ajouter la methode de tri - en utilisant sortString sur le nom de famille

2020-11-16 19:33 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +      pagination: { sortBy: 'name', descending: true, page: 1, rowsPerPage: 15 },
ascending : true plutot pourquoi par ordre decroissant ?

2020-11-16 19:33 UTC, sophiemoustard commented on src/core/helpers/rbac.js
> +  { name: 'ni management elearning courses info' },
en fait tu pourrais definir vendorAdminRoutes = [...trainingOrgnaisationManagerRoutes]; ce serait plus simple

2020-11-17 10:48 UTC, KennyCallegari commented on src/core/helpers/rbac.js
> +  { name: 'ni management elearning courses info' },
👌

2020-11-17 10:48 UTC, KennyCallegari commented on src/core/helpers/rbac.js
> +  { name: 'ni management elearning courses info' },
done

2020-11-17 10:48 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/TextMedia.vue
> +      card: { text: { required }, media: { publicId: required, link: required, type: required } },
done

2020-11-17 10:48 UTC, KennyCallegari commented on src/modules/vendor/router/routes.js
> +          // parent: 'management' à ajouter ?
done

2020-11-17 10:48 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +      pagination: { sortBy: 'name', descending: true, page: 1, rowsPerPage: 15 },
done

2020-11-17 10:48 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +          style: 'min-width: 200px; width: 70%',
done

2020-11-17 11:23 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    <ni-profile-header title="ICI LE TITRE DE LA COURSE" />
done

2020-11-17 11:34 UTC, sophiemoustard approved these changes

2020-11-17 11:47 UTC, felix-commits approved these changes

2020-11-17 11:53 UTC, merged