COM-1629 add option group in TitleTextMedia
sophiemoustard/alenvi-webapp pull request #805
Opened 2020-11-17 15:08 UTC by felix-commits

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : possibilité d'ajout des medias de type audio et video

2020-11-17 15:11 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
>    },
Il faut ajouter **type: required**
```
card: {
  title: { required },
  text: { required },
  media: { publicId: required, link: required, type: required }
},
```

2020-11-17 15:13 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
> +  },
Je suis pas sûr mais je pense qu'on peut mettre ça dans templateMixin vu que c'est la même chose que dans TextMedia

2020-11-17 15:25 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
>    },
tu es sur? parce que il ny a pas sur `TextMedia` et ca me met une erreur ```
validation.$touch is not a function
    _callee$ templateMixin.js:77
```

2020-11-17 15:25 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
> +  },
bien vu je change ca

2020-11-17 16:36 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
>    },
Malheureusement, je ne peux pas tester ce soir, du coup on peut laisser ça comme ça et je ferai une PR pour l'ajouter sur TextMedia / TitleTextMedia si on en a besoin

2020-11-17 16:36 UTC, KennyCallegari approved these changes

2020-11-18 07:16 UTC, sophiemoustard requested changes

2020-11-18 07:16 UTC, sophiemoustard commented on src/core/components/CourseProgress.vue
> +  name: 'CourseProgress',
tu peux l'appeler juste Progress

2020-11-18 07:16 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
>            name: 'status',
tu peux appeler cette colonne `progress` plutot pour etre coherent

2020-11-18 07:16 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +    'course-progress': CourseProgress,
'ni-progress': Progress du coup suite a mon retour precedent

2020-11-18 07:40 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
> +      @input="updateCard('media.type')" :disable="isUploading || !!card.media.publicId" />
tu peux ajouter `:error="$v.card.media.type.$error"`

2020-11-18 07:41 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
>        card: { title: { required }, text: { required }, media: { publicId: required, link: required } },
il faut que tu mette text et media a la ligne 
et la bonne syntaxe est `media: { publicId: { required }, link: { required } }`
en plus tu peux ajouter `type: { required }` dans media

2020-11-18 07:42 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
>    },
cf mon retour la syntaxe n'est pas la bonne

2020-11-18 10:26 UTC, sophiemoustard approved these changes

2020-11-18 10:27 UTC, KennyCallegari approved these changes

2020-11-18 10:35 UTC, merged