COM-1603 - Disable publishment button when subProgram is not valid
sophiemoustard/alenvi-webapp pull request #814
Opened 2020-11-20 17:07 UTC by KennyCallegari

- [] J'ai verifié la fonctionnalite sur mobile - NP

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Je ne peux pas publier de sous programme s'il n'est pas valid -> via le virtual areStepsValid

2020-11-23 08:46 UTC, felix-commits approved these changes

2020-11-23 08:48 UTC, sophiemoustard requested changes

2020-11-23 08:48 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          @click="validateSubProgramPublishment(subProgram)" :flat="false" :disable="!subProgram.areStepsValid" />
plutot que de bloquer le clique, plutot mettre un NotifyWarning => "Ce sous programme contient des erreurs."

2020-11-23 08:57 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          @click="validateSubProgramPublishment(subProgram)" :flat="false" :disable="!subProgram.areStepsValid" />
ça marche, j'étais parti là dessus au début mais dans le ticket c'est bien précisé de disable le clique.

2020-11-23 08:58 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileContent.vue
> +          @click="validateSubProgramPublishment(subProgram)" :flat="false" :disable="!subProgram.areStepsValid" />
je crois qu'on avait le meme avis avec kenny, on a commencé par faire comme tu dis mais romain avait écrit bloquer le clic sur jira

2020-11-23 15:43 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        }
sur une ligne

2020-11-23 15:49 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileContent.vue
> +        }
done

2020-11-24 12:53 UTC, sophiemoustard approved these changes

2020-11-24 12:54 UTC, merged