COM-1658 add category select to program creation
sophiemoustard/alenvi-webapp pull request #828
Opened 2020-11-27 16:36 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : le champs de la categorie apparait lors de la creation d'un programme

2020-11-27 16:47 UTC, sophiemoustard requested changes
cf mon retour du back il faut que tu formattes ton payload pour renvoyer une tableau categories

2020-11-27 17:18 UTC, KennyCallegari approved these changes

2020-11-30 15:50 UTC, KennyCallegari approved these changes

2020-11-30 17:39 UTC, sophiemoustard requested changes

2020-11-30 17:39 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
> +      newProgram: {},
name: '', category: ''

2020-11-30 17:44 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
> +        if (e.data.statusCode === 403) {
dans le `validateCategoryDeletion` tu peux verifier le category.porgramCount et s'il y en a return NotifyWarning

2020-12-01 08:31 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
> +        if (e.data.statusCode === 403) {
et tu peux mettre `if (e.status === 403)` plutot

2020-12-01 11:19 UTC, sophiemoustard approved these changes

2020-12-01 12:53 UTC, merged