Com 1655 - Tabs
sophiemoustard/alenvi-webapp pull request #829
Opened 2020-11-27 16:54 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendor

- Périmetre roles : rof / admin

- Cas d'usage : 
Sur la page profile d'une formation e-learning, il y a désormais 2 onglet : suivi et accès. Suivi contient la liste des apprenants et leur progression. Accès contient les règles d'accès déjà existante.

Pas dans cette PR : 
ajout de règle
suppression de règle

2020-11-27 19:38 UTC, sophiemoustard requested changes

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +<template>
ce fichier est un onglet - ce n'est pas une page => il faut  le mettre dans l'arborescence de `components` et non de `pages`
les `q-page` ne sont que pour les pages, ce qui est relié a une url - la tu n'es pas sur une page mais sur un onglet donc pas de `q-page`
de plus le standard pour le nom des onglet c'est `Profile${nom de l'onglet}` donc ici ProfileAccess

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +<template>
idem pour ce fichier

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +import ELearningCourseAccess from './ELearningCourseAccess';
dans la webapp on n'utilise que des imports absolus, jamais relatifs

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        progress: this.getCourseProgress(trainee.steps),
je crois que tu n'as plus besoin de faire ca car Ulysse a fait la modif dans le back et cette route renvoie la progression de la formation egalement

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        progress: this.getCourseProgress(trainee.steps),
`getCourseProgress` cette methode est utilisée a 2 endroits dans le front et normalement le back le gere pour les 2 donc peux tu faire cette modification egalement ?

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        }
sur une ligne

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +  },
dans le router quand on veut acceder cette page `ni management elearning courses info`, si on veint de la page `ni users learners info` il faut rediriger vers cet onglet

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    const course = await Courses.getById(this.courseId);
tu pourrais sauvegarder cet appel dans vuex pour ne pas avoir a le faire dans la page et dans l'onglet `ProfileFollowUp`

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    this.courseName = get(course, 'subProgram.program.name');
c'est a mettre dans un methode refreshCOurse qui est appelé dasn le created

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +<template>
tu pourrais regarder l'utilité des q-page + le fonctionnement avec q-layout pour mieux comprendre ca

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +    <ni-title-header title="Règle d'accès" class="row q-mb-xl" />
ici tu ne peut pas utiliser ca car ce n;est pas un header que tu veux

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +    <ni-title-header title="Règle d'accès" class="row q-mb-xl" />
ce qui aurait pu te mettre la puce a l'oreille : le design n'est pas rescpecter par rapport aux autres pages similaires. sur ces onglets, les titres ne sont pas aussi gros + pas de padding autour - tout eat aligné sur la gauche

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +  <q-page class="vendor-background" padding>
idem

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +    <ni-table-list :data="learners" :columns="columns" :loading="tableLoading" :pagination.sync="pagination"
ut pourrais ajouter un titre a ce tableau

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +      <ni-responsive-table :data="accessRules" :columns="columns" :pagination.sync="pagination">
dans ce tableau il faut aussi que tu geres le placeholder quand il n'y a pas de regle d'acces - cf la maquette. pour ca tu peux utiliser le slot `no-data` de q-table a ajouter a ResponsiveTable

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +        NotifyNegative('Erreur lors de la récupération des catégories.');
ce n'est pas une categorie

2020-11-27 19:38 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +          style: 'min-width: 110px; width: 10%',
en as tu besoin ? surtout que tu as 70% et 10% c'est etrange

2020-11-30 09:06 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +<template>
done

2020-11-30 09:07 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +<template>
done

2020-11-30 09:07 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +import ELearningCourseAccess from './ELearningCourseAccess';
done

2020-11-30 10:24 UTC, felix-commits reviewed
deux retours déjà notés par Sophie, réduire la taille de "_Règle d'accès_", et ajouter un label "_Pas de règle - la formation est en libre accès_" si le tableau est vide

2020-11-30 11:02 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        progress: this.getCourseProgress(trainee.steps),
Je veux bien qu'on fasse ça ensemble, j'ai cherché comment faire mais je n'y arrive pas

2020-11-30 11:10 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        progress: this.getCourseProgress(trainee.steps),
J'ai refacto ProfileCourses par contre

2020-11-30 11:10 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        }
done

2020-11-30 11:23 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +  },
Je ne suis pas redirigé vers ELearningCourseProfile depuis ni users learners info, c'est un bug à corriger je pense

2020-11-30 12:27 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    const course = await Courses.getById(this.courseId);
done

2020-11-30 12:27 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +    this.courseName = get(course, 'subProgram.program.name');
done

2020-11-30 12:42 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +    <ni-title-header title="Règle d'accès" class="row q-mb-xl" />
tout à fait !
done

2020-11-30 12:42 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +  <q-page class="vendor-background" padding>
done

2020-11-30 12:46 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +    <ni-table-list :data="learners" :columns="columns" :loading="tableLoading" :pagination.sync="pagination"
done

2020-11-30 13:52 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +        NotifyNegative('Erreur lors de la récupération des catégories.');
done

2020-11-30 15:02 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +        progress: this.getCourseProgress(trainee.steps),
done

2020-11-30 15:14 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +  },
done

2020-11-30 15:14 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseAccess.vue
> +      <ni-responsive-table :data="accessRules" :columns="columns" :pagination.sync="pagination">
done
Effectivement avec no data label il y avait l'icone warning noire

2020-11-30 15:15 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseFollowUp.vue
> +          style: 'min-width: 110px; width: 10%',
done

2020-11-30 15:56 UTC, felix-commits commented on src/core/components/table/ResponsiveTable.vue
> +          <span>{{ noDataLabel }}</span>
tu peux rajouter` <em>` pour mettre en italique

2020-11-30 16:17 UTC, felix-commits commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
tu peux utiliser un `<q-separator />` sous le `<span>` plutot

2020-11-30 16:17 UTC, felix-commits commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
(d'ailleurs j'ai limpression qu'il y a deux separators qui se chevauchent sur le haut)

2020-11-30 16:40 UTC, KennyCallegari commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
bien vu

2020-11-30 16:47 UTC, sophiemoustard requested changes

2020-11-30 16:47 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +        await this.$store.dispatch('course/fetchCourse', { courseId: this.courseId });
puisqu'on le mets dans le store, il faut l'enlever quand on quitte la page

2020-11-30 16:47 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    <p class="text-weight-bold q-mb-xs">Règle d'accès</p>
tu peux enlever le q-mb-sm pour etre coherent avec les autres et respecter les espacements

2020-11-30 17:05 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    <p class="text-weight-bold q-mb-xs">Règle d'accès</p>
done

2020-11-30 17:06 UTC, KennyCallegari commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
done mais je n'arrive pas à régler le séparator du haut. @sophiemoustard, une idée ?

2020-11-30 17:08 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +        await this.$store.dispatch('course/fetchCourse', { courseId: this.courseId });
done

2020-11-30 17:53 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +        await this.$store.dispatch('course/fetchCourse', { courseId: this.courseId });
je ne vois pas le changement

2020-11-30 18:02 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
dans le fichier `table.styl`
pour la classe `.table-responsive` ligne 113, tu as un moment l.152
```
 @media screen and (min-width: 768px)
    .q-table__middle
      margin: 0 10px
```
tu peux ajouter pour retirer le padding et uniformiser les marges
```
.q-table__bottom
      margin: 0 10px
      padding: 0
```

2020-11-30 18:02 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +        <div class="full-width row q-gutter-sm grey-text justify-center">
ici tu peux enlever `row q-gutter-sm `

2020-11-30 18:03 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +          <span class="text-italic">{{ noDataLabel }}</span>
et la tu peux mettre q-pb-sm sur le noDataLabel pour mettre de l'espace entre le label et le separator

2020-12-01 08:31 UTC, KennyCallegari commented on src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
> +        await this.$store.dispatch('course/fetchCourse', { courseId: this.courseId });
beforeDestroy ne fonctionne pas ?

2020-12-01 08:31 UTC, KennyCallegari commented on src/core/components/table/ResponsiveTable.vue
> +        <div class="full-width row q-gutter-sm grey-text justify-center">
done

2020-12-01 08:31 UTC, KennyCallegari commented on src/core/components/table/ResponsiveTable.vue
> +          <span class="text-italic">{{ noDataLabel }}</span>
done

2020-12-01 08:53 UTC, KennyCallegari commented on src/core/components/table/ResponsiveTable.vue
> +    border-bottom: 1px solid $middle-grey;
top ça marche bien

2020-12-01 10:37 UTC, sophiemoustard approved these changes

2020-12-01 11:20 UTC, felix-commits approved these changes

2020-12-01 12:17 UTC, merged