Com 1662
sophiemoustard/alenvi-webapp pull request #836
Opened 2020-12-01 17:39 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : vendor

- Périmetre roles : admin / rof / coach

- Cas d'usage : 
J'ai maintenant un bouton pour copier toutes les adresses mails des apprenants.
Refacto : ajout d'un multiColorsButton, utilisé pour HistoryFeed et récupéré ici.

2020-12-01 17:49 UTC, KennyCallegari reviewed
Je n'ai pas eu d'erreur lint en local mais lorsque j'ai push j'en ai eu (j'avais nommé handle-copy-success en camelCase au lieu de kebab-case). Vous savez d'où ça peut venir ?

2020-12-01 18:15 UTC, sophiemoustard requested changes

2020-12-01 18:15 UTC, sophiemoustard commented on src/core/components/MultiColorsButton.vue
> +<template>
Ici tu mélanges 2 choses :
- Créer un composant `BiColorButton` qui est composer de 2 boutons (un icone et un texte) de couleurs différentes (icone en rose et texte en noir)
- Créer un composant pour gerer la copie 

Il faut faire les deux et c'est super d'avoir pris l'initiative. Par contre il ne faut pas mélanger les deux car : 
- quand tu veux copier tu n'as pas besoin du @click
- quand tu veux cliquer tu n'as pas besoin du copy

Tu peux du coup faire 2 composants :)

2020-12-01 18:15 UTC, sophiemoustard commented on src/core/components/MultiColorsButton.vue
> +  .button-container
ce style n'est pas a mettre dans ce composant mais dans le parent au moment ou il est appelé pour qu'il soit vraiment generique

2020-12-01 18:15 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +        <p style="flex: 1" class="text-weight-bold">{{ tableTitle }}</p>
on n'utilise pas trop style comme ca et en plus je pense que la ca ne marche pas 
il faut plutot mettre un align-self sur le <ni-multi-color-button

2020-12-01 18:15 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +      const formattedTraineesEmails = traineesEmails.reduce((acc, value) => `${acc},${value}`);
tu peux chainer le map et le reduce et du coup ne pas avoir a creer tes variables `traineesEmails` et `formattedTraineesEmails` car tu pourras return direct

2020-12-02 09:49 UTC, KennyCallegari commented on src/core/components/MultiColorsButton.vue
> +<template>
effectivement, je vois la logique derrière.
done

2020-12-02 10:00 UTC, KennyCallegari commented on src/core/components/MultiColorsButton.vue
> +  .button-container
done

2020-12-02 10:01 UTC, KennyCallegari commented on src/core/components/courses/TraineeTable.vue
> +        <p style="flex: 1" class="text-weight-bold">{{ tableTitle }}</p>
done mais ça marche bien 😄 
Qu'est-ce qui te faisait dire que ça ne marche pas ?

2020-12-02 10:02 UTC, KennyCallegari commented on src/core/components/courses/TraineeTable.vue
> +      const formattedTraineesEmails = traineesEmails.reduce((acc, value) => `${acc},${value}`);
done

2020-12-02 10:50 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +        <p style="flex: 1" class="text-weight-bold">{{ tableTitle }}</p>
oui tu as raison ca foncionne j'ai oublié de mettre a jour mon commentaire apres etre allé verifier. je pensais qu'il fallait mettre des accolades

2020-12-02 10:51 UTC, sophiemoustard commented on src/core/components/CopyButton.vue
> +    size: { type: String, default: 'sm' },
default en md plutot comme les autres pour etre plus coherent

2020-12-02 10:53 UTC, sophiemoustard commented on src/core/components/CopyButton.vue
> +    handleCopySuccess () {
on pourrait juste mettre copy-success 
le `@` c'est un raccourci du `v-on` donc de maniere literale ca donnerait `v-on:copy-success` et ce qui a plus de sens que `v-on:hanlde-copy-success` qu'en penses tu ?

2020-12-02 10:54 UTC, sophiemoustard commented on src/core/components/CopyButton.vue
> +<template>
tu pourrais utiliser ce composant aussi sur l'onglet admin la ou on copie le lien de la convocation

2020-12-02 11:01 UTC, sophiemoustard reviewed
le texte du bouton est vraiment en tout petit...

2020-12-02 11:32 UTC, KennyCallegari commented on src/core/components/courses/TraineeTable.vue
> +        <ni-multi-color-button class="q-mb-md" icon="content_copy" label="Copier les adresses e-mail" size="sm"
done, je suis bien d'accord avec toi, j'allais poser la question à Romain

2020-12-02 11:32 UTC, KennyCallegari commented on src/core/components/CopyButton.vue
> +    size: { type: String, default: 'sm' },
done

2020-12-02 11:34 UTC, KennyCallegari commented on src/core/components/CopyButton.vue
> +    handleCopySuccess () {
oui c'est mieux
done

2020-12-02 11:35 UTC, KennyCallegari commented on src/core/components/CopyButton.vue
> +<template>
Ce composant va changer de fonctionnalité dans la PR que je dev en ce moment même.
Je change ça quand même ?

2020-12-02 13:42 UTC, sophiemoustard approved these changes

2020-12-02 13:47 UTC, felix-commits approved these changes
genial ! tu pourrais aussi refacto ligne 33 39 et 81 de ProfileAdmin

2020-12-02 14:04 UTC, merged