Com 1659
sophiemoustard/alenvi-webapp pull request #840
Opened 2020-12-02 16:49 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : je peux ajouter une catégorie

2020-12-03 08:58 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      newCategory: { name: '' },
ce champs peut juste etre une string non ? `newCategoty: ''`

2020-12-03 09:18 UTC, sophiemoustard requested changes

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +      <q-btn no-caps class="full-width modal-btn" label="Ajouter au programme" color="primary" :loading="loading"
Ajouter la categorie comme label plutot

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +        .map(c => ({ label: c.name, value: c._id, disable: !!this.categories.find(e => e._id === c._id) }))
ce serait peut etre mieux de filtrer les options pour ne pas afficher celle utilisées non ?

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +    this.categoryOptions = await Categories.list();
il vaut mieux faire cette appel dans le composant parent car comme un programme peut avoir plusieurs categories, on va sans doute en ajouter plusieurs d'affiler et donc ce serait dommage de faire plusiuers fois l'appel

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      <p class="text-weight-bold">Catégories</p>
il faut mettre tout ce bloc (<p> + q-card) dans un nouvelle div avec un `q-mb-xl` pour resepcter les espacement
(et donc le sortir de la `<div class="q-mb-xl">` qui commence l.4 )

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +          style: 'width: 92%',
on pourrait mettre `flex: 1` plutot que width non ?

2020-12-03 09:18 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        const payload = (path === 'categories') ? this.formatCategoryPayload() : set({}, path, value.trim());
on s'etait dit qu'on creait un nouvelle route non ? POST /programs/_id/categories

2020-12-03 12:42 UTC, KennyCallegari requested changes

2020-12-03 12:42 UTC, KennyCallegari commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +        .map(c => ({ label: c.name, value: c._id, disable: !!this.categories.find(e => e._id === c._id) }))
Je te conseille de faire le filter en dehors de la modale. Je l'ai fait dans ProfileAccess si tu veux un exemple

2020-12-03 12:42 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      newCategory: { name: '' },
Ça m'avait créé un warning lorsque j'avais fait ça sur AccessRuleCreationModal, regarde si c'est pareil pour toi

2020-12-03 12:42 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      return payload;
saut de ligne 😄

2020-12-03 12:42 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      return payload;
Il me semble que tu peux faire :
```
return { categories:  this.program.categories.map(c => c._id).push(this.newCategory.name) };
```

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +      <q-btn no-caps class="full-width modal-btn" label="Ajouter au programme" color="primary" :loading="loading"
done

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +        .map(c => ({ label: c.name, value: c._id, disable: !!this.categories.find(e => e._id === c._id) }))
done

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/CategoryAdditionModal.vue
> +    this.categoryOptions = await Categories.list();
done

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      <p class="text-weight-bold">Catégories</p>
done

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +          style: 'width: 92%',
j'ai l'impression que ca ne produit rien..

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      return payload;
j'ai limpression que le push ne réussi que une fois le tableau initialisé (le payload généré est différent)

2020-12-03 14:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        const payload = (path === 'categories') ? this.formatCategoryPayload() : set({}, path, value.trim());
ah! justement j'ai cru comprendre que tu voulais eviter de multiplier les routes

2020-12-03 20:45 UTC, sophiemoustard requested changes

2020-12-03 20:45 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        .sort((a, b) => a.label.localeCompare(b.label));
tu peux utiliser `formatAndSortOptions`

2020-12-03 20:45 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +    this.categories = await Categories.list();
met ca dans une methode `refreshCategories` avec un try/catch

2020-12-03 20:45 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        const payload = (path === 'categories') ? this.formatCategoryPayload() : set({}, path, value.trim());
vu ensmeble on fait les deux routes POST et DELETE et non la GET

2020-12-03 21:00 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      newCategory: { name: '' },
sur le parent tu peux mettre `:new-category.sync="newCategory"` et sur le select tu peux mettre `@input="$emit('update:new-category', $event)"`
et comme l'enfant ne modifie pas la props mais demande au parent de le faire 
https://fr.vuejs.org/v2/guide/components-custom-events.html#Modificateur-sync

2020-12-03 21:00 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      <q-card class="no-shadow">
pas de `class="no-shadow"`

2020-12-04 13:27 UTC, sophiemoustard requested changes

2020-12-04 13:27 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        this.categoryAdditionModal = false;
a enlever

2020-12-04 13:27 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        .onCancel(() => NotifyPositive('Suppression annulée.'));
retrait

2020-12-04 15:04 UTC, KennyCallegari approved these changes

2020-12-04 15:04 UTC, KennyCallegari commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +                  <ni-button class="row no-wrap table-actions" icon="close" :disable="program.categories.length <= 1"
ça serait pas plus cohérent avec l'icon remove ?

2020-12-04 15:29 UTC, sophiemoustard commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +                  <ni-button class="row no-wrap table-actions" icon="close" :disable="program.categories.length <= 1"
on ne supprime pas mais on retire dans notre cas

2020-12-04 16:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +      <q-card class="no-shadow">
done

2020-12-04 16:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        .sort((a, b) => a.label.localeCompare(b.label));
je n'arrive pas a comprendre comment mais j'obtiens une erreur avec cette methode

2020-12-04 16:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +    this.categories = await Categories.list();
done

2020-12-04 16:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        this.categoryAdditionModal = false;
done

2020-12-04 16:54 UTC, felix-commits commented on src/modules/vendor/components/programs/ProfileInfo.vue
> +        .onCancel(() => NotifyPositive('Suppression annulée.'));
done

2020-12-04 18:07 UTC, sophiemoustard approved these changes

2020-12-04 19:15 UTC, merged