COM-1655 - Add delete route
sophiemoustard/alenvi-webapp pull request #846
Opened 2020-12-04 18:27 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Je peux supprimer une règle d'accès

2020-12-04 18:58 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    openConfirmDeletionModal (accessRuleId) {
le standard c'est validateAccessRuleDeletion

2020-12-04 19:01 UTC, sophiemoustard requested changes

2020-12-04 19:01 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +                  <ni-button icon="delete" @click="() => openConfirmDeletionModal(col.value)" />
@click="openConfirmDeletionModal(col.value)"

2020-12-07 12:56 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    openConfirmDeletionModal (accessRuleId) {
done

2020-12-07 12:57 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +        .onCancel(() => NotifyPositive('Retrait annulé.'));
done

2020-12-07 12:57 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +        this.refreshCourse();
done

2020-12-07 12:57 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +                  <ni-button icon="delete" @click="() => openConfirmDeletionModal(col.value)" />
done

2020-12-07 13:24 UTC, felix-commits approved these changes
ligne 66 `width: 92%` rend un peu mieux que 85 mais je ne sais pas si c'est une bonne pratique, aussi tu peux remonter les `datas` au dessus des `computed`!

2020-12-07 13:37 UTC, sophiemoustard approved these changes

2020-12-07 14:02 UTC, sophiemoustard requested changes

2020-12-07 14:02 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    <q-card style="width: 75%">
pourquoi as tu mis cette width ? 
par coherence avec les autres tableaux, il vaudrait mieux laisser 100%

2020-12-07 14:02 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    <q-card style="width: 75%">
Pour me rapprocher du design

2020-12-07 14:07 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +    <q-card style="width: 75%">
c'est une erreur de Romain - en fait quand on reprend des composants existants, Romain passe moins de temps sur les maquettes car il se dit qu'on refait comme ça qui existe d'habitude. Il vaut mieux garder la cohérence global du design de l'app - c'est a ça que servent nos composants réutilisables et notre design system (encore en construction)
De maniere generale, la maquette n'est pas la verité absolue - il faut avoir un regard critique, la confronter a l'existant et s'il faut, la remettre en cause

2020-12-07 14:08 UTC, sophiemoustard requested changes

2020-12-07 14:08 UTC, sophiemoustard commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +      <ni-simple-table :data="accessRules" :columns="columns" :pagination.sync="pagination" class="q-mr-lg q-ml-lg"
tu peux mettre q-mx-lg pour fusionner les 2

2020-12-07 14:09 UTC, KennyCallegari commented on src/modules/vendor/components/courses/ProfileAccess.vue
> +      <ni-simple-table :data="accessRules" :columns="columns" :pagination.sync="pagination" class="q-mr-lg q-ml-lg"
done

2020-12-07 14:16 UTC, felix-commits approved these changes

2020-12-07 14:30 UTC, merged