Com 1691 - refacto qcm/qcu/questionAnswers
sophiemoustard/alenvi-webapp pull request #856
Opened 2020-12-09 14:58 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
qcuFalsyAnswers, qcmAnswers et questionAnswers sont fondus en un seul champ qAnswers.
L'utilisation des qcm et des qcu se fera sous la même forme que question answer :
- ajout des champs answer en plus via un bouton
- passage par les routes /{_id}/answers (POST, PUT, DELETE)

Dans cette PR :
- uniquement la refonte en un seul champ
- le fait que qcm et qcu ne soit plus comme avant est voulu (préparation à l'ajout de réponse par bouton)

2020-12-09 15:08 UTC, sophiemoustard requested changes

2020-12-09 15:08 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      <div v-for="(qAnswer, i) in card.qAnswers" :key="i" class="answers">
idem qcAnswers

2020-12-09 16:21 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      <div v-for="(qAnswer, i) in card.qAnswers" :key="i" class="answers">
done

2020-12-09 16:53 UTC, sophiemoustard approved these changes

2020-12-10 09:13 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> -        await Cards.updateById(this.card._id, this.formatAnswersPayload());
ici pourquoi tu n'appelles pas `await Cards.updateAnswer(...)` ?

2020-12-10 09:13 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
> -        await Cards.updateById(this.card._id, { qcuFalsyAnswers: this.formatQcuFalsyAnswersPayload() });
ici pourquoi tu n'appelles pas `await Cards.updateAnswer(...)` ?

2020-12-10 09:25 UTC, felix-commits reviewed
tu peux supprimer `MULTIPLE_CHOICE_QUESTION_MAX_ANSWERS_COUNT` des constants

2020-12-10 13:00 UTC, felix-commits approved these changes

2020-12-10 13:02 UTC, merged