Com 1691 - post
sophiemoustard/alenvi-webapp pull request #863
Opened 2020-12-11 14:13 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Je peux ajouter une réponse aux qcm et qcu.

2020-12-11 15:27 UTC, felix-commits approved these changes

2020-12-11 15:27 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
> +      <ni-button class="add-button" icon="add" label="Ajouter une réponse" color="primary" @click="addAnswer"
peut etre le metre a droite comme questionAnswers

2020-12-11 15:27 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      <ni-button class="add-button" icon="add" label="Ajouter une réponse" color="primary" @click="addAnswer"
peut-être le mettre a droite comme questionAnswers

2020-12-11 16:01 UTC, felix-commits commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      <ni-button class="add-button" icon="add" label="Ajouter une réponse" color="primary" @click="addAnswer"
en gros harmoniser tous les boutons `ajouter une réponse` soit a droite soit a gauche :)

<img width="761" alt="Capture d’écran 2020-12-11 à 16 59 53" src="https://user-images.githubusercontent.com/70573684/101925636-6050a180-3bd2-11eb-89a4-53f399826a8f.png">

<img width="769" alt="Capture d’écran 2020-12-11 à 16 59 33" src="https://user-images.githubusercontent.com/70573684/101925648-63e42880-3bd2-11eb-9a9e-8e0d7a4a7c17.png">

2020-12-14 07:37 UTC, sophiemoustard requested changes

2020-12-14 07:37 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +    <div class="q-my-lg answers-container">
tu pourrais simplifier le html : 
- tu enleves cette div
- tu mets une `q-mb-lg` sur l'input de la question et le bouton d'ajout d'un reponse
- tu ajoutes une classe `container` sur la premiere div de ce composant (celle qui pour le moment n'a pas de classe)

2020-12-14 07:37 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
>      <div class="q-my-lg answers">
avec le meme raisonnement qu'au dessus tu peux enlever cette div

2020-12-14 07:37 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
> +    <div class="q-my-lg answers">
idem

2020-12-14 10:58 UTC, sophiemoustard requested changes

2020-12-14 10:58 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      flex-direction: column
souci d'indentation

2020-12-14 13:01 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +    <div class="q-my-lg answers-container">
done

2020-12-14 13:01 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
>      <div class="q-my-lg answers">
done

2020-12-14 13:01 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
> +    <div class="q-my-lg answers">
done

2020-12-14 13:01 UTC, KennyCallegari commented on src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
> +      flex-direction: column
done

2020-12-14 13:19 UTC, sophiemoustard approved these changes

2020-12-14 14:12 UTC, merged