Com 1691 - delete
sophiemoustard/alenvi-webapp pull request #864
Opened 2020-12-11 17:18 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Je peux supprimer une réponse à un qcm, qcu et question answer.

2020-12-14 14:35 UTC, felix-commits reviewed
il faudrait peut-etre faire un QDialog "etes-vous sur de vouloir supprimer cette réponse?"

2020-12-14 14:42 UTC, felix-commits reviewed
peut-etre qu'il faudrait harmoniser la couleur du bouton d'ajout et de suppression (plutôt que rose/gris) ?
<img width="210" alt="Capture d’écran 2020-12-14 à 15 40 44" src="https://user-images.githubusercontent.com/70573684/102094622-d1869380-3e22-11eb-8825-931e86f7a105.png">

2020-12-14 17:24 UTC, sophiemoustard requested changes

2020-12-15 09:09 UTC, felix-commits approved these changes

2020-12-15 09:10 UTC, sophiemoustard approved these changes

2020-12-15 09:10 UTC, merged