Com 1693 post delete
sophiemoustard/alenvi-webapp pull request #871
Opened 2020-12-15 16:58 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Suppression et ajout de falsyGapAnswer via la route voulue

2020-12-16 07:55 UTC, felix-commits approved these changes

2020-12-16 11:51 UTC, sophiemoustard requested changes

2020-12-16 11:51 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
> -    <div class="q-mb-lg row gutter-profile answers">
la il faut que tu gardes cette div mere pour que les champs soient en 2 colonnes. comme le texte est cours, c'est plus joli 
par contre tu peux enlever le `q-mb-lg`

2020-12-16 15:50 UTC, sophiemoustard requested changes

2020-12-16 15:50 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
> +    width: 50%
suite a ce que je t'ai raconté plus haut, tu peux l'enlever

2020-12-16 15:50 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
> +      <div v-for="(answer, i) in card.falsyGapAnswers" :key="i" class="answers">
puisque tu as defini ton parent comme etant une row, tu peux definir ses enfants donc ces div la comme col-... en l'occurence ici `col-md-6 col-xs-12`
ce sont des classses bootstrap : quand tu definis un element avec une classse `row` ca le decoupe en 12 colonnes et tu peux ensuite spécifier combien de colonne prennent chaque enfant (en l'occurence ici on veut une demi ligne donc si colonne sur ordi et une ligne entiere don 12 colonne sur telephone)

2020-12-16 15:50 UTC, sophiemoustard commented on src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
> +      <div v-for="(answer, i) in card.falsyGapAnswers" :key="i" class="answers">
une fois que tu as fait tu pourras voir que la div prends bien col-6 mais que l'input et le bouton ne remplisse pas toute la div => du coup la tu pourras mettre un `flex: 1` sur tes inputs

2020-12-17 11:12 UTC, sophiemoustard approved these changes

2020-12-17 11:13 UTC, merged