Com 1737 design system grey palette
sophiemoustard/alenvi-webapp pull request #888
Opened 2020-12-28 15:48 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : aidant

Changements global:
- Ajout d'un fichier CSS `colors.styl` qui permet d'ajouter nos gris à la palette quasar (`color="grey-400"`, `color="grey-300"`...)
- Le gris par défaut de la palette quasar (#9e9e9e) est remplacé par notre grey-400 (#9B9B9B)
toutes les props `color="grey"` de la webapp prennent le nouveau gris.
- La sideBar possède les nouveaux gris

Changements locaux:
- plusieurs gris encodés en dur dans l'interface aidant sont à présent en variables stylus (soit le même gris soit le plus proche)
- La couleur des icones est harmonisée vers `$dark-grey` / `grey-800`

2020-12-28 16:04 UTC, KennyCallegari approved these changes

2020-12-28 16:04 UTC, KennyCallegari commented on src/css/drawer.styl
> +            color: $dark-grey
ces changements de couleur ne sont pas exactement pareil, tu as vu ça avec romain ?
+ same pour tout le fichier

2020-12-28 16:10 UTC, felix-commits commented on src/css/drawer.styl
> +            color: $dark-grey
en effet.. dans la PR l'objectif est d'harmoniser les gris en réduisant aux 4 nuances de gris qu'on a déjà dans `quasar.variables`. pour l'instant on s'occupe que de l'interface aidant, mais si sidebar est commune a toutes les interfaces, elle fait bien partie de l'interface aidant.. il faudra valider avec Sophie et Romain tous ces changements car en effet, le gris de nos icones en sideBar ne faisaient pas parti des gris que l'on souhaite garder... dans ma proposition il sont légerement plus foncé.. a voir ce qui est le mieux...

2020-12-28 16:14 UTC, felix-commits commented on src/core/components/form/DateInput.vue
> +        <q-icon name="event" class="cursor-pointer" @click="focus" color="grey-800">
très bonne remarque! enfaite quand on définit dans un .styl une classe
.text-ma-couleur {
  color: #ffff;
}
.bg-ma-couleur {
  background: #ffff;
}
cela rajoute `ma-couleur` dans les couleurs de quasar

c'est ici https://quasar.dev/style/color-palette#Adding-Your-Own-Colors

2020-12-28 16:21 UTC, KennyCallegari commented on src/css/drawer.styl
> +            color: $dark-grey
Hésite pas à le mettre dans le commentaire de ton ticket / de demander à Romain ce qu'il en pense 😄

2020-12-29 09:26 UTC, sophiemoustard commented on src/css/colors.styl
> +  color: $dark-grey;
en fait ici le but serait de ne plus avoir de `$dark-grey` dans toute l'app
donc il faudrait que tu renommes `$dark-grey` en `grey-800` partout

2020-12-29 09:26 UTC, sophiemoustard commented on src/css/colors.styl
> +  color: $dark-grey;
et idem pour les autres

2020-12-29 11:02 UTC, sophiemoustard commented on src/core/components/form/DateInput.vue
> +        <q-icon name="event" class="cursor-pointer" @click="focus" color="grey-800">
ici on est plus sur du grey-600 j'ai l'impression

2020-12-29 11:04 UTC, sophiemoustard commented on src/core/components/form/DateRange.vue
> -    border: 1px solid $middle-grey
j'ai l'impression que cette classe n'est pas utilisée

2020-12-29 11:17 UTC, sophiemoustard requested changes

2020-12-29 11:17 UTC, sophiemoustard commented on src/core/components/form/FileUploader.vue
> +        color: $grey-400
il y aussi un `#d0d0d0` a changer ligne 118

2020-12-29 11:17 UTC, sophiemoustard commented on src/css/app.styl
> +  color: $grey-800
il faudrait supprimer cette classe et utiliser `.text-grey-800` du coup

2020-12-29 11:17 UTC, sophiemoustard commented on src/css/app.styl
> +  background-color: $grey-300
tu pourrais supprimer cette classe et utiliser `bg-grey-300`

2020-12-29 11:17 UTC, sophiemoustard commented on src/css/chip.styl
> +    background: $grey-800
ligne 34 dans ce fichier tu peux mettre un grey-600

2020-12-29 13:12 UTC, felix-commits commented on src/css/app.styl
> +  color: $grey-800
tout a fait

2020-12-29 13:34 UTC, sophiemoustard approved these changes

2020-12-29 13:34 UTC, merged