Com 1744 - add extension for absence
sophiemoustard/alenvi-webapp pull request #907
Opened 2021-01-07 10:33 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : vendor

- Périmetre roles : coach / admin / vendor

- Cas d'usage : 
Je peux créer un absence sur le planning auxiliaire qui est le prolongement d'une absence existante

2021-01-07 16:52 UTC, sophiemoustard commented
tu peux ajouter un peu de marge en dessous de la checkbox 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/24521863/103920072-21e6cd80-5111-11eb-90d0-aaa4c73f8689.png"> comme sur celle d'annulation par exemple

2021-01-07 16:53 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +          <q-checkbox v-model="isExtendedAbsence" label="Prolongation" dense />
il ne faut l'afficher que pour les maladies / arrets de travail / paternité / maternité / congé parental

2021-01-07 16:55 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +        e => e.absenceNature === this.newEvent.absenceNature && e.absence === this.newEvent.absence
tu n'as pas besoin de mettre absenceNature car quand elle est horaire c'est forcement une absence injustifiée et il n'y a pas de prolongation pour ces absences la

2021-01-07 17:01 UTC, sophiemoustard requested changes

2021-01-07 17:38 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +          <q-checkbox v-model="isExtendedAbsence" label="Prolongation" dense />
done

2021-01-07 17:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +        e => e.absenceNature === this.newEvent.absenceNature && e.absence === this.newEvent.absence
done

2021-01-07 17:42 UTC, cmolle reviewed
Il faudrait trier les absences pour que ce soit les plus recentes qui apparaissent en premier

2021-01-07 17:43 UTC, cmolle commented
J'ai un soucis d'affichage quand je selectionne l'absence, rien ne s'affiche

2021-01-07 17:44 UTC, cmolle commented
Il faudrait mettre l'extension en champs required si c'est une prolongation, non ?

2021-01-07 18:20 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +          <ni-select v-if="isExtendedAbsence" :value="formatAbsence(newEvent.extension)"
effectivement !
Je n'avais pas bien compris les options du select ( la relation entre value / label). ça reste encore une petit zone de flou pour moi mais je me suis renseigné et j'ai mieux compris

2021-01-07 18:20 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +            @focus="getAbsences" />
réglé avec le problème du dessous !

2021-01-07 18:20 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +            @focus="getAbsences" />
et done pour le 1er commentaire aussi

2021-01-07 18:35 UTC, KennyCallegari commented
> Il faudrait trier les absences pour que ce soit les plus recentes qui apparaissent en premier

Je n'ai pas réussi à le faire avec mon '.sort()'. Tu saurais comment faire ?

2021-01-08 09:06 UTC, felix-commits reviewed
j'arrive a créer un evenement prolongation avant la date de l'évenement prolongé, je me dit que ca ne devrait pas etre rendu possible..
aussi je peux créer un evenement prolongation a partir d'un evenement lui meme deja la prolongation d'un autre evenement, on a le droit à ça aussi?

2021-01-08 09:42 UTC, felix-commits commented
d'ailleurs j'ai remarqué un bug hors de ce tickets sur le planning: j'ai l'impression que si on glisse un événement vers une date hors contrat, l'événement disparait

2021-01-11 08:20 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +        CESSATION_OF_WORK_CHILD,
CESSATION_OF_WORK_RISK et CESSATION_OF_WORK_RISK ne sont pas dans la liste
par contre WORK_ACCIDENT et TRANSPORT_ACCIDENT oui

2021-01-11 08:27 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +          .sort((a, b) => moment(a.startDate) - moment(b.startDate))
il faudait trier dans l'autre sens - il y a plus de chance pour que l'absence a prolonger soit une absence recente

2021-01-11 08:31 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +      return `Cette absence est une prolongation de ${nature.label.toLowerCase()} commencant le ${startDate}`;
a mettre en gris, italique et avec une marge de 8px en dessous

+ il manque un . a la fin de ta phrase

2021-01-11 08:39 UTC, sophiemoustard requested changes

2021-01-11 08:39 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +          </div>
sur une ligne

2021-01-11 08:39 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +    async updateAbsence (event) {
pourquoi as tu `resetAbsenceType` et `resetAbsence` ?

2021-01-11 08:39 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +          <q-checkbox v-show="canExtendAbsence" class="q-mb-sm" :value="isExtendedAbsence" @input="getAbsences"
si je le selectionne, il faut que le champ prolongation soit obligatoire

2021-01-11 09:27 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +          </div>
J'ai mis les modifications liées à l'édition dans une nouvelle PR pour plus de clarté

2021-01-11 10:12 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +          .sort((a, b) => moment(a.startDate) - moment(b.startDate))
done

2021-01-11 10:14 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +        CESSATION_OF_WORK_CHILD,
done

2021-01-11 10:15 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +      return `Cette absence est une prolongation de ${nature.label.toLowerCase()} commencant le ${startDate}`;
Je l'ai fait dnas mon autre PR du coup, je la push quand toute l'édition est complétée

2021-01-11 10:18 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +    async updateAbsence (event) {
Je n'ai pas de resetAbsence. Tu parles de resetExtension ?

2021-01-11 10:26 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +          <q-checkbox v-show="canExtendAbsence" class="q-mb-sm" :value="isExtendedAbsence" @input="getAbsences"
done
je ne suis pas sûr de ma méthode

2021-01-11 10:30 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +            required-field in-modal caption="Absence" :options="extendedAbsenceOptions" />
ici deja tu peux mettre `:required-field="isExtendedAbsence"`

2021-01-11 10:31 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +    async updateAbsence (event) {
pardon la question etait sur updateAbsence et resetAbsenceType

2021-01-11 10:31 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +          .sort((a, b) => moment(b.startDate) - moment(a.startDate))
peut tu utiliser new Date ? comme on va virer moment ^^

2021-01-11 10:34 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      isExtendedAbsence: false,
pour qu'on puisse mettre cette validation dans vuelidate il faudrait mettre `isExtendedAbsence` dans le parent - comme pour la gestion de `isCancelled`

2021-01-11 10:39 UTC, cmolle commented on src/modules/client/components/planning/EventCreationModal.vue
> +      if (this.isExtendedAbsence && !this.newEvent.extension) return NotifyWarning('Choisissez l\'absence à prolonger');
Je pense que tu peux ajouter dans la validation de newEvent dans PlanningActionMixin

2021-01-11 10:45 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +            required-field in-modal caption="Absence" :options="extendedAbsenceOptions" />
Le champ n'est visible que si isExtendedAbsence est présent donc je m'étais dis que ce n'étais pas la peine. Qu'en penses-tu ?

2021-01-11 10:49 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +          .sort((a, b) => moment(b.startDate) - moment(a.startDate))
bien vu ! done

2021-01-11 11:04 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +    async updateAbsence (event) {
pardon je parlais de updateAbsence

2021-01-11 11:08 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      isExtendedAbsence: false,
done

2021-01-11 11:08 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      if (this.isExtendedAbsence && !this.newEvent.extension) return NotifyWarning('Choisissez l\'absence à prolonger');
done

2021-01-11 11:29 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +            required-field in-modal caption="Absence" :options="extendedAbsenceOptions" />
oui tu as raison

2021-01-11 11:33 UTC, sophiemoustard approved these changes

2021-01-11 12:09 UTC, cmolle approved these changes

2021-01-11 12:52 UTC, merged