Com 1751 upload attendanceSheets
sophiemoustard/alenvi-webapp pull request #908
Opened 2021-01-07 13:44 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : formateur

- Cas d'usage : je peux uploader mes feuilles d'émargement

2021-01-07 13:57 UTC, felix-commits commented on src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
> -      <ni-responsive-table :data="categories" :columns="columns" :pagination.sync="pagination">
ce changement n'a pas de rapport avec la PR
c'est un petit fix pour l'affichage du tableau de catégories

2021-01-07 14:20 UTC, KennyCallegari commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :options="traineesOption" caption="Apprenant" required-field />
traineeOptions

2021-01-07 14:20 UTC, KennyCallegari commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :options="dateOption" caption="Date" required-field />
dateOption**s**

2021-01-07 14:20 UTC, KennyCallegari commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    },
Pourquoi as-tu besoin de ça ?

2021-01-07 17:11 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +    <ni-select v-if="course.type == INTRA" :value="newAttendanceSheet.date" @blur="validations.date.$touch"
c'est mieux de mettre un triple egale

2021-01-07 17:20 UTC, sophiemoustard requested changes

2021-01-07 17:20 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +              </template>
sur une ligne

2021-01-07 17:20 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +        label: moment(date.startDate).format('DD MMMM YYYY'),
on pourrait garder le meme format poru toutes les dates DD/MM/YYYY

2021-01-07 17:20 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    columns () {
ici tu peux definir les 3 colonne Date / Apprenant / Actions et utiliser la props `visibleColumns` pour n'afficher que les bonnes

2021-01-07 17:20 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      no-type in-modal />
ici il ne faut pas que tu reutilise `documentUpload` mais uniquement reprendre fonctionnement du ni-input avec le file

2021-01-07 17:28 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +                  <ni-button icon="download" color="primary" type="a" target="_self" :href="props.row.file.link" />
target="_blank"

2021-01-08 11:45 UTC, KennyCallegari approved these changes

2021-01-11 08:09 UTC, cmolle commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +    dateOptions () {
Il ne faut prendre qu'une fois la date si il y a plusieurs creneaux sur une meme date. Je pense que tu peux soit utiliser un Set (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Set) soit grouper par dates les creneaux.

2021-01-11 08:09 UTC, cmolle commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +                  <ni-button icon="download" color="primary" type="a" target="_blank" :href="props.row.file.link" />
Je ne vois pas ce bouton

2021-01-11 08:09 UTC, cmolle commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      newAttendanceSheet: { course: this.profileId, file: null, trainee: undefined, date: undefined },
On peut peut etre initiliaser uniquement avec course ? Je trouve ca etrange de definir des champs à null et undefined. Tu en penses quoi ?

2021-01-11 08:09 UTC, cmolle commented on src/modules/client/components/documents/DocumentUpload.vue
> +    noType: { type: Boolean, default: false },
Tu as change ce composant, mais j'ai l'impression que tu ne l'utilises pas, est-ce voulu ?

2021-01-11 09:52 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :options="dateOptions" caption="Date" required-field />
done

2021-01-11 09:53 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +  components: {
done

2021-01-11 09:55 UTC, felix-commits commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      newAttendanceSheet: { course: this.profileId, file: null, trainee: undefined, date: undefined },
done

2021-01-11 09:56 UTC, felix-commits commented on src/modules/client/components/documents/DocumentUpload.vue
> +    noType: { type: Boolean, default: false },
done

2021-01-11 10:00 UTC, felix-commits commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +                  <ni-button icon="download" color="primary" type="a" target="_blank" :href="props.row.file.link" />
étrange.. et tu peux voir le delete a coté quand meme ou aucun des deux?

2021-01-11 11:54 UTC, cmolle commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +                  <ni-button icon="download" color="primary" type="a" target="_blank" :href="props.row.file.link" />
Oui je vois le delete.
Mais trop bizarre que tu la vois et pas moi ^^ Je crois qu'on met file_download d'habitude comme icone, tu pourrais essayer comme ca ?

2021-01-11 12:04 UTC, cmolle commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      const dateOptionsSet = new Set([...this.course.slots.map(date => moment(date.startDate).startOf('d').format())]);
Je crois qu'on utilise plutot toDate() habituellement plutot que format()

2021-01-11 12:54 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error="validations.date.$error" :error-message="REQUIRED_LABEL" @input="update($event, 'date')" in-modal
REQUIRED_LABEL est la valeur par defaut donc pas besoin de le mettre

2021-01-11 12:54 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error="validations.date.$error" :error-message="REQUIRED_LABEL" @input="update($event, 'date')" in-modal
idem pour ceux d'en dessous

2021-01-11 13:14 UTC, sophiemoustard commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error-message="REQUIRED_LABEL" required-field />
ici aussi pour le REQUIRED_LABEL

2021-01-11 13:19 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      const dateOptionsSet = new Set([...this.course.slots.map(date => moment(date.startDate).startOf('d').format())]);
done

2021-01-11 13:21 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      const dateOptionsSet = new Set([...this.course.slots.map(date => moment(date.startDate).startOf('d').format())]);
done

2021-01-11 13:21 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error="validations.date.$error" :error-message="REQUIRED_LABEL" @input="update($event, 'date')" in-modal
done

2021-01-11 13:21 UTC, felix-commits commented on src/core/components/courses/AttendanceSheetAdditionModal.vue
> +      :error-message="REQUIRED_LABEL" required-field />
done

2021-01-11 15:37 UTC, cmolle approved these changes

2021-01-11 15:51 UTC, KennyCallegari approved these changes

2021-01-11 16:31 UTC, sophiemoustard approved these changes

2021-01-11 17:34 UTC, merged