Com 1744 edition
sophiemoustard/alenvi-webapp pull request #915
Opened 2021-01-12 15:02 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach / admin / auxiliaire

- Cas d'usage :
Je peux editer une absence qui est un prolongement d'une autre absence

Ce qu'il manque : l'export

Ce que je n'ai pas réussi à faire : parfois lorsque ma connexion est un peu lente, le fait d'appeler la fonction qui récupère les options au @focus n'a pas le temps de s'exécuter. J'ai cherché une solution mais je ne trouve pas. Avez vous une idée ?

2021-01-12 15:04 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +            @focus="getExtendedAbsenceOptions" />
Parfois cette solution ne fonctionne pas (cf description), vous auriez une autre solution ?

2021-01-12 16:54 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
pourquoi tu mets ca dans `updateCustomer` ? on est ici dans le cas d'une intervention et `extendedAbsenceOptions` c'est pour une absence

2021-01-12 16:55 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
pourquoi tu le vide au moment du submit ? s'il y a une erreur dans l'enregistrement, ca risque de poser des probleme

2021-01-12 16:55 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
pourquoi cet ajout ?

2021-01-12 17:05 UTC, sophiemoustard requested changes

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +            <div class="q-mb-md infos">{{ extensionInfo }}</div>
et d'ailleurs, si on rend la prolongation editable, il faut aussi pouvoir la supprimer en fait - et ce message d'information perd de son sens...
tu peux l'enlever, et mettre la checkbox a la place

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +      this.extendedAbsenceOptions = [];
idem

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +      this.extendedAbsenceOptions = [];
idem

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
pourquoi le vide tu ? on ne peut plus le choisir une absence dans ce cas...
il faudrait relancer la requete peut etre. et d'ailleurs comme au changement de type d'absence d'ailleurs. tu pourrais utiliser watch peut etre pour ca

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +        });
je crois que ca passse sur une ligne

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +    async getExtendedAbsenceOptions () {
il faudrait l'appeler ausssi au changement d'absence et de dates non ?

2021-01-12 17:05 UTC, sophiemoustard commented on src/modules/client/components/planning/EventEditionModal.vue
> +            <ni-select in-modal v-if="editedEvent.extension" :value="editedEvent.selectedExtendedAbsence"
comme on edite la valeur, on n'a plus besoin de la phrase de detail donc pas besoin de populer en back et donc a priori ici on peut garder extension

2021-01-12 17:26 UTC, cmolle reviewed
Lorsque j'ouvre la modale d'edition, je ne vois pas a quelle absence est lie ma prolongation, c'est normal ? (et je crois que l'absence n'apparait plus dans le select)
<img width="549" alt="Capture d’écran 2021-01-12 à 18 25 50" src="https://user-images.githubusercontent.com/22516544/104349759-9fd91900-5503-11eb-9ea6-ab868273528a.png">

2021-01-12 17:26 UTC, cmolle commented on src/modules/client/components/planning/EventEditionModal.vue
> +    async getExtendedAbsenceOptions () {
Est-ce qu'il ne faudrait pas mettre cette methode dans la mixin ? Elle doit etre assez similaire a celle dans eventcreationmodal non ?

2021-01-13 10:44 UTC, sophiemoustard commented
Vue ensemble Kenny, on ne rend pas la prolongation editable

2021-01-13 14:40 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
done

2021-01-13 14:40 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
done

2021-01-13 14:40 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
done

2021-01-13 14:41 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +              caption="Prolongation" :options="extendedAbsenceOptions" @focus="getExtendedAbsenceOptions"
cf dernier commentaire, l'édition est annulée.

2021-01-13 14:41 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +            <div class="q-mb-md infos">{{ extensionInfo }}</div>
cf dernier commentaire, l'édition est annulée.

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +      this.extendedAbsenceOptions = [];
done

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +      this.extendedAbsenceOptions = [];
done

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      this.extendedAbsenceOptions = [];
done, c'est ce que je voulais faire, je n'avais pas pensé aux watch

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +        });
done

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +    async getExtendedAbsenceOptions () {
done

2021-01-13 14:42 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +            <ni-select in-modal v-if="editedEvent.extension" :value="editedEvent.selectedExtendedAbsence"
cf dernier commentaire, l'édition est annulée.

2021-01-13 14:43 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +    async getExtendedAbsenceOptions () {
cf dernier commentaire, l'édition est annulée.
Pour ton commentaire du dessus, c'était une feature pour ne pas sélectionner l'absence qui est déjà l'extension.

2021-01-13 16:30 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
> +      await this.$emit('update:newEvent', { ...this.newEvent, absence: event });
il faudrait peut etre que tu vide `extension` ici la prolongation ne sera forcement pas la meme si tu passe de accident du travail a congé maternité par exemple

2021-01-13 16:33 UTC, sophiemoustard requested changes

2021-01-13 16:33 UTC, sophiemoustard commented on src/modules/client/mixins/planningActionMixin.js
> +      if (event.extension) payload.extension = event.extension._id;
je penses que tu peux l'enlever non ? car on le modifie pas

2021-01-13 16:43 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
> +      await this.$emit('update:newEvent', { ...this.newEvent, absence: event });
Normalement `extension` se reset parce que le watch sur` newEvent.extension` appelle` getAbsences()` qui update `newEvent.extension` à ''.
L.263

2021-01-13 16:46 UTC, KennyCallegari commented on src/modules/client/mixins/planningActionMixin.js
> +      if (event.extension) payload.extension = event.extension._id;
done

2021-01-13 17:08 UTC, cmolle commented
Comme on ne peut pas modifier la prolongation, il faudrait peut etre enlever (ou desactivé) le bouton de la modale ?

2021-01-14 07:39 UTC, sophiemoustard commented
> Comme on ne peut pas modifier la prolongation, il faudrait peut etre enlever (ou desactivé) le bouton de la modale ?

@cmolle l'evenement en lui meme est toujours modifiable mais pas la notion de prolongation pour simplifier dans un premier temps

2021-01-14 07:40 UTC, sophiemoustard approved these changes

2021-01-14 13:31 UTC, felix-commits reviewed
j'arrive toujours a faire plusieurs prolongations sur un même evenement est-ce voulu?

2021-01-14 13:31 UTC, felix-commits commented on src/modules/client/components/planning/EventEditionModal.vue
> +          <ni-datetime-range caption="Dates et heures de l'évènement" :value="editedEvent.dates" required-field
j'ai systématiquement une 400 lorsque j'essaie de modifier un evenement qui est une prolongation, est-ce normal que ca soit empeché? si oui il faudrait disable tous les inputs de la modale et surtout l'upload gdrive car ça m'a permis de garder l'evenement mais sans justificatif (cf le malade imaginaire de JB Molière)

2021-01-14 13:31 UTC, felix-commits commented on src/modules/client/components/planning/EventCreationModal.vue
>              @blur="validations.extension.$touch" :error="validations.extension.$error" />
(je devrais pouvoir fermer la modale que si ni-file uploader est vide, sinon on peut laisser des fichiers errants en base)

2021-01-14 14:20 UTC, KennyCallegari commented on src/modules/client/components/planning/EventEditionModal.vue
> +          <ni-datetime-range caption="Dates et heures de l'évènement" :value="editedEvent.dates" required-field
J'ai retravaillé ce point justement

2021-01-14 14:20 UTC, KennyCallegari commented on src/modules/client/components/planning/EventCreationModal.vue
>              @blur="validations.extension.$touch" :error="validations.extension.$error" />
bonne suggestion 😄 
@cmolle @sophiemoustard vous en pensez quoi ?

2021-01-14 14:26 UTC, sophiemoustard commented on src/modules/client/components/planning/EventCreationModal.vue
>              @blur="validations.extension.$touch" :error="validations.extension.$error" />
c'est un bonne suggestion mais hors perimetre de ce ticket :)

2021-01-14 14:26 UTC, sophiemoustard commented
> j'arrive toujours a faire plusieurs prolongations sur un même evenement est-ce voulu?

oui et c'est d'ailleurs tout a fait possible dans la réalité

2021-01-14 15:24 UTC, cmolle approved these changes

2021-01-14 15:37 UTC, felix-commits approved these changes

2021-01-14 15:38 UTC, merged