Com 1756
sophiemoustard/alenvi-webapp pull request #930
Opened 2021-01-19 16:33 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client / vendor

- Périmetre roles : rof / admin / coach

- Cas d'usage : 
Dans le répertoire apprenant, je vois désormais deux nouvelles colonnes : le nombres d'activités réalisées et le nombre de jours depuis la dernière activité

2021-01-19 16:44 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +        : 'jamais';
Ce n'étais pas précisé dans le ticket mais je trouvais ça mieux que rien. (Même chose pour le style des colonnes). J'ai posé la question à Romain, j'attends son retour

2021-01-20 07:57 UTC, cmolle commented on src/core/mixins/learnerDirectoryMixin.js
> +        const learners = await Users.learnerList(companyId ? { company: companyId } : null);
Que penses-tu de passer {} plutot que null ?

2021-01-20 07:57 UTC, cmolle commented on src/core/mixins/learnerDirectoryMixin.js
> +        ? `${moment(moment().diff(moment(user.lastActivityHistory.updatedAt))).format('d')} jour(s)`
Tu peux utilises la methode formatQuantity de utils pour avoir le s quand il faut :)

2021-01-20 07:57 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +        : 'jamais';
tu peux laisser vide sinon ... qui permet de reperer plus rapidement qu'il n'y a rien

2021-01-20 08:34 UTC, sophiemoustard requested changes

2021-01-20 08:34 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +          style: 'width: 60%',
tu peux mettre 50% ici, 60 je trouve que ca fait beaucoup

2021-01-20 08:34 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +          style: 'width: 10%',
tu peux enlever ceux la, ca se mettra bien automatiquement

2021-01-20 09:26 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +        ? `${moment(moment().diff(moment(user.lastActivityHistory.updatedAt))).format('d')} jour(s)`
Oui ! D'ailleurs je vais essayé de ne pas utiliser moment() aussi

2021-01-20 10:27 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +        : 'jamais';
vu avec Romain : on met '-'

2021-01-20 10:27 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +        const learners = await Users.learnerList(companyId ? { company: companyId } : null);
done

2021-01-20 10:29 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +          style: 'width: 60%',
done

2021-01-20 10:30 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +          style: 'width: 10%',
done

2021-01-20 14:08 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +        ? `${moment(moment().diff(moment(user.lastActivityHistory.updatedAt))).format('d')} jour(s)`
done

2021-01-20 14:17 UTC, cmolle approved these changes

2021-01-20 14:18 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +      const days = parseInt(Math.ceil(duration / 1000 / 60 / 60 / 24), 10);
Dites moi ce que vous en pensez, ça remplace `moment().diff().format('d')`.
Surtout que je me suis rendu compte que s'il y a plus d'un 1 mois d'écart cette méthode est erronée (elle se réinitialise à 0)

2021-01-20 14:39 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +      const days = parseInt(Math.ceil(duration / 1000 / 60 / 60 / 24), 10);
je valide ! tu pourrais creer un helper `date.js` pour commencer a repertorier ces methodes

2021-01-20 14:41 UTC, felix-commits commented on src/core/mixins/learnerDirectoryMixin.js
> +          label: 'Dernière activité il y a...',
ca serait peut-etre plus lisible d'écrire juste `Derniere activité` et mettre `il y a` sur chaque ligne

2021-01-20 14:43 UTC, KennyCallegari commented on src/core/mixins/learnerDirectoryMixin.js
> +          label: 'Dernière activité il y a...',
ça fait chargé de mettre il y a sur chaque ligne

2021-01-20 14:45 UTC, felix-commits approved these changes

2021-01-20 15:41 UTC, sophiemoustard approved these changes

2021-01-21 07:41 UTC, cmolle approved these changes

2021-01-21 16:59 UTC, cmolle approved these changes

2021-01-21 17:08 UTC, sophiemoustard approved these changes

2021-01-21 17:08 UTC, merged