Com 1757
sophiemoustard/alenvi-webapp pull request #935
Opened 2021-01-20 17:06 UTC by cmolle

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client/vendeur

- Périmetre roles : coach/admin/rof

- Cas d'usage : Sur la page d'un apprenant, j'ai un encadre qui m'indique son nombre de formations en cours/terminees et le nombre d'activtes realisees. 
Verifier egalement l'affichage sur le tableau de bord suite à la creation d'un composant pour l'affichage des chiffres.

Interrogation: Le fait de tester la pr de Kenny sur l'affichage de la colonnes du nombre d'activites sur le repertoire apprenant m'a fait me rendre compte que je comptais certains historiques d'activites deux fois (j'ai donc ajoute le uniqBy).
Ca me fait m'interroger sur le fait qu'on calcule certaines stats dans le front et que potentiellement on peut avoir des incoherences. Pour cette stat en particulier, on pourrait populer le champs dans le Users.getById (une fois la pr de Kenny merge), mais je m'interrogeais plus globalement sur les stats qui se retrouvent a plusieurs endroits dans l'app ou des stats differentes mais liées (ex: sur le tableau de bord le nombre d'activites peut etre calcule en sommant les activites de tous les utilisateurs).

2021-01-20 18:06 UTC, sophiemoustard requested changes

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      return uniqBy(this.eLearningCourses
je crois qu'on ne veut pas faire de uniq car si l'utilisateur l'a fait deux fois on veut la compter deux fois

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +        <ni-expanding-table :data="courses" :columns="columns" :loading="loading">
Lea VP a 6 formations en tout et dans le tableau je n'en vois que 5
je pense qu'il faut rajouter un `rowPerPage: 0` quelques part pour ne pas qu'il limite

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      return uniqBy(this.eLearningCourses
je crois qu'on ne veut pas faire de uniq car si l'utilisateur l'a fait deux fois on veut la compter deux fois

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +    formatQuantity,
ou l'utilises tu ?

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      return this.eLearningActivitiesCompleted > 1 ? 'activités eLearning réalisées' : 'activité eLearning réalisée';
il manque un .length non ?
car la j'ai ca 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/24521863/105216138-739c4880-5b52-11eb-99e1-7dabae026b48.png">

2021-01-20 18:06 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      return this.eLearningActivitiesCompleted > 1 ? 'activités eLearning réalisées' : 'activité eLearning réalisée';
idem pour les formations

2021-01-21 07:48 UTC, cmolle commented on src/core/components/learners/ProfileCourses.vue
> +      return uniqBy(this.eLearningCourses
Normalement le uniqBy est fait sur l'_id de l'activityHistory et non de l'activity. Ca permet de ne pas compter deux fois lorsqu'une activityHistory se refere a la meme activite dans deux formations differentes.

2021-01-21 07:51 UTC, cmolle commented on src/core/components/learners/ProfileCourses.vue
> +    formatQuantity,
Je ne l'utilise plus, je l'ai enleve :)

2021-01-21 07:56 UTC, cmolle commented on src/core/components/learners/ProfileCourses.vue
> +        <ni-expanding-table :data="courses" :columns="columns" :loading="loading">
J'ai mis directement cette valeur par defaut dans expanding-table

2021-01-21 07:57 UTC, cmolle commented on src/core/components/learners/ProfileCourses.vue
> +      return this.eLearningActivitiesCompleted > 1 ? 'activités eLearning réalisées' : 'activité eLearning réalisée';
Done !

2021-01-21 09:00 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      return uniqBy(this.eLearningCourses
ah oui je vois ! bien vu !

2021-01-21 09:01 UTC, sophiemoustard approved these changes

2021-01-21 09:18 UTC, felix-commits commented on src/core/components/learners/ProfileCourses.vue
> +      const formation = this.eLearningCoursesOnGoing.length > 1 ? 'formations' : 'formation';
tu pourrais utiliser la fonction `formatQuantity` de utils ? (sur les deux suivants je vois que c'est plus commode juste avec un ternaire)

2021-01-21 09:18 UTC, felix-commits commented on src/core/components/learners/ProfileCourses.vue
> +              <div class="col-9 stats-container">
class="col-9 column justify-around"

2021-01-21 09:18 UTC, felix-commits commented on src/core/components/learners/ProfileCourses.vue
> +              <div class="col-3 indicators-container stats-container">
class="col-3 text-right q-pr-md"

2021-01-21 09:24 UTC, cmolle commented on src/core/components/learners/ProfileCourses.vue
> +      const formation = this.eLearningCoursesOnGoing.length > 1 ? 'formations' : 'formation';
Enfait la fonction formatQuantity renvoie aussi la quantite: elle renvoie "3 formations" et non "formations". Comme on ne veut pas le meme style sur le chiffre et le texte j'ai prefere ne pas utilise formatQuantity.

2021-01-21 09:29 UTC, felix-commits approved these changes

2021-01-21 10:01 UTC, KennyCallegari approved these changes

2021-01-21 10:01 UTC, merged