Com 1754
sophiemoustard/alenvi-webapp pull request #943
Opened 2021-01-25 17:32 UTC by KennyCallegari

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : client

- Périmetre roles : coach / admin

- Cas d'usage :
Dans la page profile d'un apprenant, côté client, je peux maintenant cliquer sur une formation pour avoir accès à sa page profil, qui contient la liste des apprenants de cette formation. Je ne peux voir que les apprenants de mon entreprise.

2021-01-25 17:59 UTC, felix-commits reviewed
je contredis la stratégie tech donc c'est a prendre avec des pincettes: n'était-ce pas possible de réutiliser le ProfileFollowUp plutot que de créer une mixin et un nouveau composant presque identique ELearningCourseProfile? grace a une computed isVendorInterface on pourrait envoyer ou non la query company?

2021-01-25 17:59 UTC, felix-commits commented on src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
> +        NotifyNegative('Erreur lors de la récupération des formations');
participants

2021-01-26 10:10 UTC, cmolle commented on src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
> +      course: [],
Course n'est pas un objet ?

2021-01-26 13:22 UTC, sophiemoustard requested changes

2021-01-26 13:22 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +        return this.$router.push({ name: 'ni elearning courses info', params: { profileId: props.row._id } });
on utilise profileId pour toutes les pages qui utilisent `profileTabs` donc on peut laissser comme ca, pour anticiper si la page evolue

2021-01-26 14:11 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
> +        NotifyNegative('Erreur lors de la récupération des formations');
done

2021-01-26 16:22 UTC, cmolle commented on src/modules/vendor/components/courses/ProfileFollowUp.vue
> +        if (this.isClientInterface) this.course = course;
Pourquoi est-ce qu'il y en a besoin sur l'interface client et pas vendeur ?

2021-01-26 18:55 UTC, sophiemoustard requested changes

2021-01-26 18:55 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +import ProfileFollowUp from '@components/courses/ProfileFollowUp';
tu peux le laisser sur la ligne d'qu dessus pour garder tous les @components ensemble

2021-01-26 18:55 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
> +    'ni-profile-follow-up': ProfileFollowUp,
ce n'est pass un composant generique donc tu peux ne pas mettre le prefixe ni

2021-01-27 10:49 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
> +    'ni-profile-follow-up': ProfileFollowUp,
done

2021-01-27 10:49 UTC, KennyCallegari commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +import ProfileFollowUp from '@components/courses/ProfileFollowUp';
done

2021-01-27 11:02 UTC, cmolle approved these changes

2021-01-27 13:01 UTC, sophiemoustard approved these changes

2021-01-27 13:01 UTC, merged