COM-1755 learner stats
sophiemoustard/alenvi-webapp pull request #950
Opened 2021-01-29 10:05 UTC by felix-commits

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur client

- Périmetre roles : rof coach

- Cas d'usage : je vois le rapport d'utilisation des formations eLearning

2021-01-29 10:58 UTC, sophiemoustard requested changes

2021-01-29 10:58 UTC, sophiemoustard commented on src/core/components/courses/ProfileFollowUp.vue
> +        <div class="col-sm-6 col-xs-12">
on est plutot sur du col-md-6 col-xs-12 en general

2021-01-29 10:58 UTC, sophiemoustard commented on src/core/components/courses/ProfileFollowUp.vue
> +    traineesOnGoing () {
que penses tu d'ajouter Count dans le nom de la variable ? `traineesOnGoingCount` pour qu'on sache que c'est une valeur numerique et non une liste

2021-01-29 10:58 UTC, sophiemoustard commented on src/core/components/courses/ProfileFollowUp.vue
> +    traineesFinnished () {
idem

2021-01-29 10:58 UTC, sophiemoustard commented on src/core/components/courses/ProfileFollowUp.vue
> +                <div>apprenant{{ traineesOnGoing - 1 ? 's' : '' }} en cours</div>
tu pourrais utiliser `formatQuantity`

2021-01-29 10:58 UTC, sophiemoustard commented on src/core/components/courses/ProfileFollowUp.vue
> +                <div>apprenant{{ traineesFinnished - 1 ? 's' : '' }} ayant terminé</div>
idem

2021-01-29 11:21 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +                <div>apprenant{{ traineesOnGoing - 1 ? 's' : '' }} en cours</div>
comme pour @cmolle dans la PR #935 on ne peut pas utiliser `formatQuantity` car elle renvoie aussi la quantite

2021-01-29 11:23 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +        <div class="col-sm-6 col-xs-12">
done

2021-01-29 11:23 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +    traineesOnGoing () {
done

2021-01-29 11:23 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +    traineesFinnished () {
done

2021-01-29 12:03 UTC, sophiemoustard approved these changes

2021-01-29 12:07 UTC, cmolle commented on src/core/components/courses/ProfileFollowUp.vue
> +                <ni-e-learning-indicator :indicator="traineesFinnishedCount" />
finished avec un seul n

2021-01-29 12:07 UTC, cmolle commented on src/core/components/courses/ProfileFollowUp.vue
> +                <div>apprenant{{ traineesFinnishedCount - 1 ? 's' : '' }} ayant terminé</div>
Je crois qu'habituellement on met plutot traineesOnGoingCount > 1 ? 's' : ''

2021-01-29 12:47 UTC, KennyCallegari commented on src/core/components/courses/ProfileFollowUp.vue
> +    },
Est-ce qu'on peut directement le calculer comme ça : 
`this.learners.length - this.traineesOnGoingCount` ?

2021-01-29 12:47 UTC, KennyCallegari commented on src/core/components/courses/ProfileFollowUp.vue
> +    },
ça évite de parcourir deux fois la liste à chaque changement

2021-01-29 13:50 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +                <ni-e-learning-indicator :indicator="traineesFinnishedCount" />
done

2021-01-29 13:50 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
> +                <div>apprenant{{ traineesFinnishedCount - 1 ? 's' : '' }} ayant terminé</div>
done

2021-01-29 14:05 UTC, KennyCallegari reviewed
C'est voulu qu'on retrouve ce composant sur l'onglet suivi des stagiaire de la page profile d'une formation blended ? Ce n'est pas dans le figma

2021-02-01 07:10 UTC, cmolle commented on src/core/components/courses/ProfileFollowUp.vue
>  <template>
Ce composant est utilisé cote client comme page/onglet sur la page d'une formation elearning, et est utilisé uniquement pour le tableau cote vendeur. 
Je me demande s'il ne faudrait pas faire un composant pour le tableau et l'utiliser ici et cote vendeur. Je me dis que si on rajoute des choses sur cette page il faudra a chaque fois faire le cas strictly_e_learning. 
Qu'en pensez vous ?

2021-02-01 08:54 UTC, felix-commits commented on src/core/components/courses/ProfileFollowUp.vue
>  <template>
done

2021-02-01 10:41 UTC, cmolle commented on src/core/components/courses/ProfileFollowUp.vue
> +    <trainee-follow-up-table :learners.sync="learners" :profile-id="profileId" />
Que penses-tu de plutot passer a la table les learners ? On pourrait creer une mixin pour garder la logique en commun entre le e-learning et le blended ?

2021-02-01 11:20 UTC, cmolle approved these changes

2021-02-01 12:06 UTC, KennyCallegari approved these changes

2021-02-01 12:35 UTC, sophiemoustard approved these changes

2021-02-01 12:35 UTC, merged