Com 1856
sophiemoustard/alenvi-webapp pull request #958
Opened 2021-02-02 16:43 UTC by felix-commits

- [np] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach

- Cas d'usage : fix no mutating prop

1. customer creation
2. funding creation
3. funding edition
4. helper creation
5. helper edition

2021-02-02 17:32 UTC, cmolle approved these changes

2021-02-02 17:32 UTC, cmolle commented on src/modules/client/components/customers/infos/FundingEditionModal.vue
> -  },
👍

2021-02-03 08:16 UTC, sophiemoustard requested changes

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      if (prop === 'nature' && this.isFixedFunding && this.newFunding.frequency !== ONCE) {
tu pourrais creer une methode `updateNature` pour ce cas la specifique 
```
updateNature (event) {
  if (this.isFixedFunding && this.newFunding.frequency !== ONCE) {
    await this.$emit('update:newFunding', { ...this.newFunding, frequency: '' });
  }
  await this.$emit('update:newFunding', { ...this.newFunding, [prop]: event });
}
```

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +        this.newFunding.frequency = '';
pour ce cas la li faut aussi que tu utilises $emit sinon tu restes dans le meme probleme : l'enfant modifie la props qu'il recoit du parent

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +        @input="update($event, 'identity.firstname')" />
tu peux mettre un trim ici stp ?

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +        @input="update($event, 'identity.lastname')" />
idem

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'identity.lastname')" />
idem

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'identity.firstname')" />
idem

2021-02-03 08:16 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'contact.phone')" />
idem

2021-02-03 10:27 UTC, KennyCallegari commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      if (prop === 'nature' && this.isFixedFunding && this.newFunding.frequency !== ONCE) {
petite correction : 
```
updateNature (event) {
  if (this.isFixedFunding && this.newFunding.frequency !== ONCE) {
    await this.$emit('update:newFunding', { ...this.newFunding, frequency: '', nature: event });
  }
  await this.$emit('update:newFunding', { ...this.newFunding, nature: event });
}
```

2021-02-03 10:27 UTC, KennyCallegari commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      if (prop === 'nature' && this.isFixedFunding && this.newFunding.frequency !== ONCE) {
On peut aussi faire plus compréhensible en gardant la logique d'avant refacto : 
```
updateNature (event) {
  const resetFundingFrequency = this.isFixedFunding && this.newFunding.frequency !== ONCE;

  await this.$emit('update:newFunding',  resetFundingFrequency ? { ...this.newFunding, nature: event } :  { ...this.newFunding, nature: event, frequency: '' } );
}
```

2021-02-03 10:29 UTC, KennyCallegari commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      if (prop === 'nature' && this.isFixedFunding && this.newFunding.frequency !== ONCE) {
Qu'en pensez vous ?

2021-02-03 10:48 UTC, felix-commits commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'contact.phone')" />
done

2021-02-03 10:48 UTC, felix-commits commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'identity.firstname')" />
done

2021-02-03 10:48 UTC, felix-commits commented on src/modules/client/components/customers/infos/HelperEditionModal.vue
> +      @input="update($event, 'identity.lastname')" />
done

2021-02-03 10:48 UTC, felix-commits commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +        @input="update($event, 'identity.lastname')" />
done

2021-02-03 10:48 UTC, felix-commits commented on src/modules/client/components/customers/infos/HelperCreationModal.vue
> +        @input="update($event, 'identity.firstname')" />
done

2021-02-03 13:28 UTC, KennyCallegari commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      return this.update(event, 'nature');
pourquoi return et pas await ?

2021-02-03 14:38 UTC, felix-commits commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      return this.update(event, 'nature');
les deux sont équivalents non? je bascule :)

2021-02-03 14:51 UTC, sophiemoustard requested changes

2021-02-03 14:51 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      }
tu peux enlever cette partie la du coup

2021-02-03 14:52 UTC, sophiemoustard commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      return this.update(event, 'nature');
dans ce cas oui je pense que c'est equivalent

2021-02-03 15:10 UTC, felix-commits commented on src/modules/client/components/customers/infos/FundingCreationModal.vue
> +      }
done

2021-02-03 15:13 UTC, sophiemoustard approved these changes

2021-02-03 15:14 UTC, KennyCallegari approved these changes

2021-02-03 15:17 UTC, merged