Com 1844
sophiemoustard/alenvi-webapp pull request #979
Opened 2021-02-18 17:16 UTC by KennyCallegari

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : admin / coach

- Cas d'usage : 
Dans dashboard je vois un graphe des apprenants de mon entreprise sur les 6 derniers mois

2021-02-18 17:54 UTC, cmolle commented on src/core/components/lineChart/LineChart.vue
> +  name: 'ProfileFollowUp',
LineChart

2021-02-18 17:54 UTC, cmolle commented on src/core/components/lineChart/LineChart.vue
> +    options: { type: Object, required: true },
Est-ce qu'on ne pourrait pas mettre par defaut les options que l'on utilise pour l'instant ? Il y a des chances pour que ce soit toujours les memes

2021-02-19 11:01 UTC, sophiemoustard requested changes

2021-02-19 11:05 UTC, KennyCallegari commented on src/core/components/lineChart/LineChart.vue
> +import LineChart from '@components/lineChart/VueChartLineChart';
Ah oui j'ai changé par rapport au ticket, j'ai oublié de le précisé :
je trouvais VueChartLineChart plus explicite (le LineChart de VueChart)
Qu'en pensez-vous ?

2021-02-19 11:06 UTC, KennyCallegari commented on src/core/mixins/lineChartMixin.js
> +                }
Si c'est assez explicite pour vous, ça me va !

2021-02-19 11:06 UTC, KennyCallegari commented on src/core/components/lineChart/LineChart.vue
> +  name: 'ProfileFollowUp',
done

2021-02-19 11:07 UTC, KennyCallegari commented on src/core/components/lineChart/LineChart.vue
> +    options: { type: Object, required: true },
done

2021-02-19 11:08 UTC, KennyCallegari commented on src/core/components/courses/ProfileFollowUp.vue
> +import LineChart from '@components/lineChart/LineChart';
je suis d'accord, done

2021-02-19 11:09 UTC, KennyCallegari commented on src/core/components/lineChart/LineChart.vue
> +  <div>
done

2021-02-19 11:10 UTC, KennyCallegari commented on src/core/mixins/lineChartMixin.js
> +                }
done

2021-02-19 11:12 UTC, KennyCallegari commented on src/core/mixins/lineChartMixin.js
> +    getTraineeByMonth (activityHistoriesByMonth) {
Je l'ai renommé "traineeChartMixin", qu'en pensez-vous ?

2021-02-19 12:40 UTC, cmolle commented on src/core/components/lineChart/LineChart.vue
> +import LineChart from '@components/lineChart/VueChartLineChart';
Il me semble que VueLineChart on s'etait dit que ca sonnait comme un line chart de vue, c'est pour ca qu'on avait mis VueChartLine pour parler du type line de vue chart. C'est vrai que VueChartLineChart est plus explicite.

2021-02-19 12:51 UTC, cmolle commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +    <ni-line-chart title="Apprenants actifs mensuels" :chart-data="chartData" class="q-mt-md line-chart-container" />
Est-ce que tu pourrais ajouter du padding a droite ? Pour que le graphique soit aligne avec la carte du dessus.

2021-02-19 13:11 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +    <ni-line-chart title="Apprenants actifs mensuels" :chart-data="chartData" class="q-mt-md line-chart-container" />
done !

2021-02-19 13:11 UTC, KennyCallegari commented on src/core/components/lineChart/LineChart.vue
> +  <div>
On en a besoin pour le css, q-card ne réagit pas aux margin / padding

2021-02-19 15:46 UTC, ulysseferreira approved these changes

2021-02-19 17:45 UTC, sophiemoustard commented on src/core/mixins/traineeChartMixin.js
> +import { colors } from 'quasar';
trop stylé ca !!

2021-02-19 18:06 UTC, sophiemoustard requested changes

2021-02-19 18:06 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +
en imaginant la logique : 
- 1er bloc : récupération des historique (définition des dates + appel a l'api)
- 2eme bloc : Definition de la data `traineesByMonth` avec les 2 formatage successifs
tu pourrais enlever cette ligne vide (idem pour l'autre ligne que je te mentionne plus bas)

qu'en penses tu ?

2021-02-19 18:06 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        NotifyPositive('Données mises a jour.');
il manque un accent sur le a

2021-02-19 18:06 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        NotifyNegative('Erreur lors de la recupération des données.');
je crois qu'il y a un accent sur le 1er e de récupération

2021-02-19 18:06 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +    width: 50%;
en suivant la logique plus haut ce serait a appeler

2021-02-19 18:06 UTC, sophiemoustard commented on src/core/mixins/traineeChartMixin.js
> +    getTraineeByMonth (activityHistoriesByMonth) {
dans la meme logique que les autre variable que penses tu de `historiesByMonth` ?
comme on est dans le contexte du elearning, il n'y a pas de doute sur l'historique dont on parle :)

2021-02-19 18:10 UTC, sophiemoustard commented
on pourrais mettre "chiffres generaux" et "Evolution dans le temps" en plus gros que les titres des blocs blancs qu'en penses tu ?

2021-02-22 07:38 UTC, cmolle commented on src/core/components/courses/ProfileFollowUp.vue
> +      const activityHistoriesByMonth = groupBy(activityHistories, ah => this.formatMonthAndYear(ah.date));
Est-ce qu'on peut mettre cette ligne en commun dans getTraineeByMonth ?

2021-02-22 08:25 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +    <ni-line-chart title="Apprenants actifs mensuels" :chart-data="chartData" class="q-mt-md line-chart-container" />
done

2021-02-22 08:25 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        const lastSixMonthsActivityHistories = await ActivityHistories.list({
done

2021-02-22 08:26 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        NotifyPositive('Données mises a jour.');
done

2021-02-22 08:26 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        NotifyNegative('Erreur lors de la recupération des données.');
done

2021-02-22 08:27 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +    width: 50%;
à enlever ? 😄

2021-02-22 08:29 UTC, KennyCallegari commented on src/core/mixins/traineeChartMixin.js
> +    getTraineeByMonth (activityHistoriesByMonth) {
done

2021-02-22 08:32 UTC, KennyCallegari commented on src/core/components/courses/ProfileFollowUp.vue
> +      const activityHistoriesByMonth = groupBy(activityHistories, ah => this.formatMonthAndYear(ah.date));
done

2021-02-22 11:29 UTC, KennyCallegari commented
> on pourrais mettre "chiffres generaux" et "Evolution dans le temps" en plus gros que les titres des blocs blancs qu'en penses tu ?

J'ai demandé à Romain, en attendant je l'ai passé à 24px, je trouve ça un peu petit aussi

2021-02-22 14:01 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +
done

2021-02-22 14:03 UTC, KennyCallegari commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +        const activityHistoriesByMonth = groupBy(
done

2021-02-22 14:15 UTC, cmolle approved these changes

2021-02-22 18:25 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/Dashboard.vue
> +      <p class="text-weight-bold">Evolution dans le temps</p>
text-weight-bold section-title

2021-02-22 18:28 UTC, sophiemoustard requested changes

2021-02-22 18:28 UTC, sophiemoustard commented on src/core/mixins/traineeChartMixin.js
> +              )
tu peux mettre ca sur une ligne

2021-02-23 08:28 UTC, sophiemoustard approved these changes

2021-02-23 09:16 UTC, merged