COM-1919 fix bug on companyconfig
sophiemoustard/alenvi-webapp pull request #985
Opened 2021-02-22 14:34 UTC by cmolle

- [ ] J'ai verifié la fonctionnalite sur mobile -np

- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : Je peux renseigner les informations de ma structure dans Configuration generale (tester pour une structure avec/sans erp)

2021-02-22 14:47 UTC, KennyCallegari approved these changes
J'ai remarqué aussi ce bug sur les sociétés qui viennent d'être créée (dans le tableau de bord), si tu peux le régler en boyscout 😄 
![image](https://user-images.githubusercontent.com/45166809/108724030-2a5e6080-7525-11eb-83c6-3b488c9e26a8.png)

2021-02-22 15:08 UTC, sophiemoustard requested changes

2021-02-22 15:08 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CompanyConfig.vue
>        this.company = this.loggedCompany;
a-t-on besoin de ca du coup ? on pourrait passer directement en computed non ?

2021-02-22 15:11 UTC, ulysseferreira approved these changes

2021-02-22 18:47 UTC, sophiemoustard approved these changes

2021-02-22 19:42 UTC, ulysseferreira approved these changes

2021-02-23 10:23 UTC, KennyCallegari approved these changes

2021-02-23 10:52 UTC, merged