COM-1885: add pagination
sophiemoustard/alenvi-webapp pull request #989
Opened 2021-02-25 11:53 UTC by ulysseferreira

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : auxiliaires, coach, planning referent, admin 

- Cas d'usage : Sur le répertoire des auxiliaires, je peux changer la pagination et afficher toute la liste

2021-02-25 13:24 UTC, KennyCallegari commented on src/core/components/table/TableList.vue
> +          @update:pagination="$emit('update:pagination', $event)" />
`@update:pagination="update($event)"` devrait fonctionner non ?

2021-02-25 13:54 UTC, KennyCallegari commented on src/core/components/table/TableList.vue
> +          @update:pagination="$emit('update:pagination', $event)" />
Comme dans SimpleTable

2021-02-25 14:07 UTC, KennyCallegari approved these changes

2021-02-25 14:42 UTC, sophiemoustard commented on src/core/components/table/TableList.vue
>        :visible-columns="formattedVisibleColumns">
tu peux mettre ca sur 3 lignes

2021-02-25 14:42 UTC, cmolle reviewed
Sur le ticket, il est dit de changer la pagination du repertoire auxiliaire. J'ai l'impression que tu as modifie tous les TableList, est-ce voulu ?

2021-02-25 14:42 UTC, cmolle commented on src/core/components/table/TableList.vue
> +    rowsPerPage: { type: Array, default: () => [15, 50] },
Comment as-tu choisis 15 et 50 ?

2021-02-25 14:45 UTC, ulysseferreira commented on src/core/components/table/TableList.vue
>        :visible-columns="formattedVisibleColumns">
done

2021-02-25 14:53 UTC, ulysseferreira commented on src/core/components/table/TableList.vue
> +    rowsPerPage: { type: Array, default: () => [15, 50] },
parce que ça me semblait adapté au nombre d'auxiliaires qu'on a chez Alenvi mais c'est vrai que c'est peut-être pas pertinent pour d'autres structures, tu mettrais quoi toi ? (c'est corrigé pour ta question du dessus)

2021-02-25 14:59 UTC, cmolle commented on src/core/components/table/TableList.vue
> +    rowsPerPage: { type: Array, default: () => [15, 50] },
Ok ca me parait pertinent pour Alenvi en effet :) On verra a l'usage si il faut le changer :)

2021-02-25 15:04 UTC, sophiemoustard commented on src/modules/client/pages/ni/auxiliaries/Directory.vue
> +      @go-to="goToUserProfile" :rows-per-page="[15, 50]">
pourquoi n'avoir changé qu'ici et pas sur les autres repertoire ?
et tu pourrais le mettre en props non ?

2021-02-25 19:10 UTC, ulysseferreira commented on src/modules/client/pages/ni/auxiliaries/Directory.vue
> +      @go-to="goToUserProfile" :rows-per-page="[15, 50]">
done

2021-02-26 08:13 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +      @go-to="goToTrainerProfile" :rows-per-page="[5, 10, 15]" />
je doute que quelqu'un veuille n'afficher que 5 personnes ^^ - je me dis qu'on peut mettre 15 a chaque fois en minimum comme c'est le cas aujourd'hui et garder 15 / 50 / 100 comme valeur de base a mettre en valeur par defaut de la props dans le composant

2021-02-26 09:13 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> +      @go-to="goToTrainerProfile" :rows-per-page="[5, 10, 15]" />
done

2021-02-26 09:41 UTC, sophiemoustard submitted a review, later dismissed

2021-02-26 11:00 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
> +        rowsPerPage: 0,
il faut mettre 15 car quand on aura 30 formations on voudra 15 par page par défaut

2021-02-26 11:00 UTC, sophiemoustard requested changes

2021-02-26 11:00 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
> +      },
tu peux les mettre sur une ligne

2021-02-26 11:12 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
> +      },
done

2021-02-26 11:12 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
> +        rowsPerPage: 0,
done

2021-02-26 14:23 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
> +  },
tu pourrais le mettre dans la mixin `eLearningCourseDirectoryMixin` pour ne pas dupliquer l'info et avoir la meme pagination sur les 2

2021-02-26 14:24 UTC, sophiemoustard requested changes

2021-02-26 14:24 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      pagination: { sortBy: 'name', descending: false, page: 1, rowsPerPage: 15 },
idem tu pourrais le mettre dans learnerDirectoryMixin

2021-02-26 14:31 UTC, sophiemoustard commented
dans Pagination, j'ai l'impression qu'en ajoutant ca 
```
data () {
    return {
      rowsPerPage: this.options.some(o => o.value === this.pagination.rowsPerPage)
        ? this.pagination.rowsPerPage
        : 0,
    };
  },
```
ca resout le souci de Chloé

2021-02-26 14:31 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      pagination: { sortBy: 'name', descending: false, page: 1, rowsPerPage: 15 },
done

2021-02-26 14:32 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
> +  },
done

2021-02-26 16:36 UTC, sophiemoustard commented on src/core/components/table/Pagination.vue
> +  async created () {
tu n'as pas besoin de mettre `async` car tu n'as pas de methode asynchrone dans created

2021-02-26 16:36 UTC, sophiemoustard commented on src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
> +      <template #body="{ col }" :rows-per-page="[15, 50, 100, 200]">
tu ne l'as pas mis au bon endroit

2021-02-26 16:36 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      pagination: { sortBy: 'name', descending: false, page: 1, rowsPerPage: 15 },
je ne vois pas le changement

2021-02-26 16:51 UTC, sophiemoustard approved these changes

2021-02-26 16:59 UTC, cmolle approved these changes

2021-02-26 16:59 UTC, merged