COM-1886: add sticky header
sophiemoustard/alenvi-webapp pull request #990
Opened 2021-02-25 14:42 UTC by ulysseferreira

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : auxiliaires, coach, planning referent, admin

- Cas d'usage : on fixe le header du tableau sur le suivi du plan d'aide pour pouvoir le garder en scrollant (notamment sur mobile)

2021-02-25 14:55 UTC, cmolle commented on src/core/components/table/SimpleTable.vue
>        :selected="selected" :visible-columns="formattedVisibleColumns" :hide-bottom="shouldHideBottom">
Tu peux mettre plus de props sur la ligne du dessus

2021-02-25 14:55 UTC, cmolle commented on src/core/components/table/SimpleTable.vue
> +    height: 75vh
Comment as-tu defini ces valeurs ? Est-ce que c'est possible de mettre des valeurs responsives par rapport a la hauteur de l'ecran plutot que la largeur ?

2021-02-25 15:01 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
>        :selected="selected" :visible-columns="formattedVisibleColumns" :hide-bottom="shouldHideBottom">
done

2021-02-25 15:01 UTC, sophiemoustard reviewed
sur mobile tu pourrais reduire l'espace entre le titre et le tableau => par exemple sur la page Suivi des plans d'aide
dans `.title-padding` sur petit ecran, retirer le padding-bottom

2021-02-25 15:01 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +    height: 55vh
tu pourrais mettre 65 je pense. la le tableau est vraiment tout petit

2021-02-25 15:01 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +  @media screen and (min-width: 768px)
il me semble que Felix a mis en place des variables pour 768px ect

2021-02-25 15:06 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +    height: 55vh
comment as tu defini le 480 ? d'habitude on ne tl'utilises pas celui la

2021-02-25 15:19 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +    height: 75vh
done, j'ai pris les breakpoint sur internet et après j'ai regardé ce qui rendait à mon sens le mieux pour chaque écran proposé par le devtool

2021-02-25 15:23 UTC, KennyCallegari commented on src/core/components/table/SimpleTable.vue
> +.sticky-header-table
petit soucis d'indentation

2021-02-25 15:34 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
>        :selected="selected" :visible-columns="formattedVisibleColumns" :hide-bottom="shouldHideBottom">
done

2021-02-25 15:35 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +    height: 55vh
outdated (je suis passé en max-height plutôt que width)

2021-02-25 17:25 UTC, sophiemoustard commented on src/css/app.styl
> +    padding: 1rem 1rem 0rem 1rem
je pense que tu peux plutot modifier celui du dessus directement sinon il y aura conflit

2021-02-25 18:12 UTC, sophiemoustard reviewed
pour le tableau de la pahe a facturer, l'en tete n'est pas fixe car on la redefinit dans ToBill #header. peux tu regarder ?

2021-02-25 19:35 UTC, ulysseferreira commented on src/css/app.styl
> +    padding: 1rem 1rem 0rem 1rem
done

2021-02-26 08:08 UTC, cmolle commented on src/core/components/table/SimpleTable.vue
> +      height: 65vh
Que penses-tu comme height de 85vh quelque soit la hauteur de l'ecran ?

2021-02-26 08:11 UTC, cmolle commented on src/core/components/table/SimpleTable.vue
> +      height: 65vh
Que penses-tu aussi de passer a des max-height plutot ? Avec height, sur le tableau des feuilles d'emargement ca oblige le tableau a prendre beaucoup de place meme s'il n'y en a pas.

2021-02-26 08:32 UTC, sophiemoustard requested changes

2021-02-26 08:32 UTC, sophiemoustard commented on src/css/app.styl
> +    padding: 1rem 1rem 0rem 1rem
je pense que tu n'as pas push, je ne vois aps le changement

2021-02-26 08:32 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +      background-color: $grey-100
il faut que ta couleur de fond depende de si tu es sur l'interface vendeur ou client - la sur le suivi des stagiaires, on a un fond gris

2021-02-26 08:38 UTC, sophiemoustard commented
> pour le tableau de la pahe a facturer, l'en tete n'est pas fixe car on la redefinit dans ToBill #header. peux tu regarder ?

C'est aussi le cas dans ClientBalance. Dans ces composants on redefinit l'entete car on ajoute une checkbox donc on ne prend pas celle par defaut dans SImpleTable
COmme le style est defini dans SImpleTable et qu'il est restreint au perimetre de ce fichier (`scoped`) il ne peux pas s'appliquer sur les autres en-tetes.

pour resoudre le souci, tu peux mettre la definition de la classe `sticky-header-table` dans le fichier `table.styl` pour que ce soit accessible de tous les fichiers

2021-02-26 09:22 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +      height: 65vh
done

2021-02-26 09:39 UTC, KennyCallegari reviewed
Petit soucis sur ProfileFollowUp aussi
![image](https://user-images.githubusercontent.com/45166809/109283259-d9998100-781e-11eb-88a5-ef3959c31abb.png)

2021-02-26 09:45 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +      background-color: $grey-100
done

2021-02-26 10:24 UTC, cmolle commented on src/css/table.styl
> +    top: 0
Que penses-tu de creer trois classes: 
- client-background-header, vendor-background-header qui a le backgorund color
- sticky-header qui a le reste des parametres ?

2021-02-26 10:30 UTC, cmolle commented on src/css/table.styl
> +
Un espace en trop

2021-02-26 10:36 UTC, ulysseferreira commented on src/css/table.styl
> +
done

2021-02-26 10:38 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +        : 'vendor-background-header']">
tu pourrais juste mettre client-header et vendor-header qu'en penses tu ?

2021-02-26 10:38 UTC, cmolle approved these changes

2021-02-26 10:47 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +        : 'vendor-background-header']">
done

2021-02-26 10:50 UTC, sophiemoustard commented on src/core/components/table/SimpleTable.vue
> +        : 'vendor-header']">
sur une ligne du coup

2021-02-26 10:54 UTC, KennyCallegari approved these changes

2021-02-26 10:58 UTC, ulysseferreira commented on src/core/components/table/SimpleTable.vue
> +        : 'vendor-header']">
done

2021-02-26 11:01 UTC, sophiemoustard approved these changes

2021-02-26 11:01 UTC, merged