COM-1882: wip
sophiemoustard/alenvi-webapp pull request #993
Opened 2021-03-01 11:17 UTC by ulysseferreira

vue no-mutating props : 
PaymentCreationModal.vue

PaymentEditionModal.vue

CreditNoteCreationModal.vue

CreditNoteEditionModal.vue

petit soucis de sur creditNoteCreationModal, on ne peux pas mettre de montant TTC, il semblerait qu'il y ait un conflit entre inclTaxesCustomer et inclTaxesTpp et qu'il faille initialiser newCreditNote à {} au lieu de définir chaque champ pour que ça marche. Une idée de pourquoi ?

2021-03-01 16:48 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      :error="validations.customer .$error" use-input clearable />
Espace en trop entre customer et .

2021-03-01 16:48 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      :error="validations.customer .$error" use-input clearable />
A quoi sert use-input et clearable ?

2021-03-01 16:48 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +      await this.update(event, prop);
Je n'ai pas l'impression que update soit asynchrone

2021-03-01 16:48 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +      this.getEvents();
Il me semble que getEvents est asynchrone ?

2021-03-01 16:49 UTC, cmolle commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        @input="update($event, 'inclTaxesCustomer')" />
J'ai l'impression que le watcher newCreditNote.events est appelé a chaque changement de valeur et je me demande si va ne vient pas de la ducoup.

2021-03-02 15:47 UTC, KennyCallegari commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        @input="update($event, 'inclTaxesCustomer')" />
Bien vu ! Je crois avoir compris pourquoi :
v-model ne modifie que le champ `newCreditNote.inclTaxesCustomer`, alors que notre update modifie l'objet newCreditNote en entier. Donc même si le champ newCreditNote.event est en soit le même, le watcher est appelé.

J'en prends pour preuve que :
aucun watcher n'est appelé lorsqu'on utilise v-model
les watcher de newCreditNote.customer et newCreditNote.events sont appelés dès qu'un champ est modifié si on passe par update pour le modifier.

Je propose donc la solution :
```
    'newCreditNote.events': function (value) {
      if (value) {
        const prices = this.computePrices(this.newCreditNote.events);
        this.newCreditNote.exclTaxesCustomer = prices.exclTaxesCustomer;
        this.newCreditNote.inclTaxesCustomer = prices.inclTaxesCustomer;
        this.newCreditNote.exclTaxesTpp = prices.exclTaxesTpp;
        this.newCreditNote.inclTaxesTpp = prices.inclTaxesTpp;
      }
    },
```

Ou bien

```
    'newCreditNote.events': function (value) {
      if (this.newCreditNote.events) {
        const prices = this.computePrices(this.newCreditNote.events);
        this.newCreditNote.exclTaxesCustomer = prices.exclTaxesCustomer;
        this.newCreditNote.inclTaxesCustomer = prices.inclTaxesCustomer;
        this.newCreditNote.exclTaxesTpp = prices.exclTaxesTpp;
        this.newCreditNote.inclTaxesTpp = prices.inclTaxesTpp;
      }
    },
```

2021-03-02 16:14 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        @input="update($event, 'inclTaxesCustomer')" />
pour editedCreditNote.events le if (this.hasLinkedEvents) suffit à éviter ce soucis où il peut y avoir des cas où il pop ? (auquel cas il faut aussi rajouter un if (value) )

2021-03-03 10:04 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/PaymentEditionModal.vue
> +      in-modal type="date" required-field />
je crois que tu peux enlever `type=date` qui n'est pas une props de DateINput

2021-03-03 10:05 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/PaymentCreationModal.vue
>        :error="validations.date.$error" @blur="validations.date.$touch" in-modal type="date" required-field />
idem ici sur le type date

2021-03-03 10:08 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +      this.getEvents();
a creuser si en emetant un evenement qui lance une methode asynchrone, est ce asynchrone ? 🤔

2021-03-03 11:12 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
> +        @input="update($event, 'inclTaxesCustomer')" />
tres bonne analyse Kenny ! en effet dans le update on recrée l'objet newCreditNote et donc on declenche les watcher sur les champs `customer` et `events` quelque soit celui qu'on est en train de modifier 

la methode sur un watcher permet de prendre deux arguments : la nouvelle valeur et egalement l'ancienne -> https://vuejs.org/v2/guide/computed.html#Watchers est ce une piste a creuser ?

2021-03-03 17:06 UTC, sophiemoustard requested changes

2021-03-04 14:24 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/PaymentCreationModal.vue
>        :error="validations.date.$error" @blur="validations.date.$touch" in-modal type="date" required-field />
done

2021-03-04 14:26 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
>              :error="validations.events.$error" />
done

2021-03-04 15:25 UTC, sophiemoustard requested changes

2021-03-04 15:25 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/PaymentCreationModal.vue
> +      :error-message="netInclTaxesError" />
ca tient en 3 lignes

2021-03-04 15:25 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/PaymentEditionModal.vue
> +      :error-message="netInclTaxesError" />
ca tient en 3 lignes

2021-03-04 15:25 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/PaymentEditionModal.vue
> +      in-modal required-field />
ca tient en 2 ligens

2021-03-04 16:07 UTC, KennyCallegari commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +        :error="validations.date.$error" @blur="validations.date.$touch" :disable="!editedCreditNote.isEditable" />
Il faut passer ces changements dans l'autre PR, non ?

2021-03-04 17:44 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/PaymentCreationModal.vue
> +      :error-message="netInclTaxesError" />
done

2021-03-04 17:45 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/PaymentEditionModal.vue
> +      :error-message="netInclTaxesError" />
done

2021-03-04 17:45 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/PaymentEditionModal.vue
> +      in-modal required-field />
done

2021-03-04 17:50 UTC, ulysseferreira commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +        :error="validations.date.$error" @blur="validations.date.$touch" :disable="!editedCreditNote.isEditable" />
c'est juste un retour à la ligne, tu veux que je le vire ? de l'autre côté il y est pas vu qu'il :value @input et que ça prend plus de deux lignes

2021-03-04 17:52 UTC, sophiemoustard commented on src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
> +        :error="validations.date.$error" @blur="validations.date.$touch" :disable="!editedCreditNote.isEditable" />
on peut le laisser dans cette PR ce n'est pas genant :)

2021-03-04 18:17 UTC, sophiemoustard approved these changes

2021-03-05 09:14 UTC, KennyCallegari approved these changes

2021-03-05 09:14 UTC, merged