Com 1923
sophiemoustard/alenvi-webapp pull request #996
Opened 2021-03-02 14:50 UTC by KennyCallegari

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~

- [ ] J'ai verifié la fonctionnalite sur mobile - np

- Périmetre interface : client

- Périmetre roles : helper / admin

- Cas d'usage : 
Ajout d'un plan de majoration possible le 1er Janvier (qui s'applique à la place du jour férié).

__Comment tester__ :
Je n'ai pas réussi à tester l'export de paie / modale de détail sur le plan de majoration sans changer le '01/01' dans helper surcharges et draftPay par une autre date de mars / février (car on a accès qu'au 2 derniers mois sur ces données). Donc si vous avez une idée de comment faire, je la veux bien, sinon, remplacez les deux 
01/01 dans le code par une autre date de mars / février (02/02 par exemple) et appliquez les étapes suivantes avec votre nouvelle date

- Config Bénéficiaire > Ajouter une majoration le 1er janvier dans le plan de majo 'Alenvi Defaut'
- Vérifiez que votre majo apparait dans le tableau des plan de majo
- Ajoutez une intervention à une auxiliaire le 1er janvier
- Facturez cette intervention
- Ajouter un avoir pour cette intervention
- Vérifiez que la majo apparait sur les pdf d'avoir et de factu de votre bénéficiaire (profil > facturation)
- Vérifier la modale de détail des plan de majoration sur le tableau de paie
- Vérifier l’export des données de paie
- Mettez fin au contrat de l'auxiliaire concernée
- Vérifier une fin de contrat + export

2021-03-02 17:27 UTC, ulysseferreira approved these changes

2021-03-03 11:17 UTC, sophiemoustard commented on src/modules/client/components/config/SurchargeEditionModal.vue
> +        :error-message="nbrError('firstOfJanuary', validations)" />
tu dois pouvoir mettre ca sur 3 lignes

2021-03-03 11:17 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +          field: row => row.firstOfJanuary && `${row.firstOfJanuary}%`,
on pourrait avoir une methode de formatage a reutiliser partout qu'en penses tu ?

2021-03-03 12:39 UTC, KennyCallegari reviewed
La serviceHistoryModal de customerConfig n'a pas été passé en modal externe, je boyscout ça ?

2021-03-03 12:39 UTC, KennyCallegari commented on src/modules/client/components/config/SurchargeEditionModal.vue
> +        :error-message="nbrError('firstOfJanuary', validations)" />
done

2021-03-03 12:39 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +          field: row => row.firstOfJanuary && `${row.firstOfJanuary}%`,
done

2021-03-03 16:37 UTC, cmolle reviewed
Est-ce que tu penses que c'est possible de changer un peu la taille des colonnes car le tableau est en scroll meme en plein ecran ?

2021-03-03 17:05 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +      return field && `${field}%`;
tu pourrais utiliser la methode utile roundFrenchPercentage

2021-03-03 17:07 UTC, sophiemoustard requested changes

2021-03-03 17:07 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +      return (field ? moment(field).format('HH:mm') : '');
idem ici formatHoursWithMinutes

2021-03-03 17:29 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +      return (field ? moment(field).format('HH:mm') : '');
done

2021-03-03 17:29 UTC, KennyCallegari commented on src/modules/client/pages/ni/config/CustomersConfig.vue
> +      return field && `${field}%`;
done

2021-03-03 17:30 UTC, sophiemoustard requested changes

2021-03-03 17:30 UTC, sophiemoustard commented on src/core/helpers/utils.js
> +  number
tu peux le laisser sur la ligne du dessus non ?

2021-03-03 17:33 UTC, KennyCallegari commented on src/core/helpers/utils.js
> +  number
done

2021-03-04 12:46 UTC, sophiemoustard approved these changes

2021-03-04 13:40 UTC, cmolle approved these changes

2021-03-04 15:40 UTC, merged